// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/game.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleService_CreateGame_FullMethodName         = "/game.network.BattleService/CreateGame"
	BattleService_GetGameData_FullMethodName        = "/game.network.BattleService/GetGameData"
	BattleService_RegisterCharacters_FullMethodName = "/game.network.BattleService/RegisterCharacters"
	BattleService_StreamGame_FullMethodName         = "/game.network.BattleService/StreamGame"
)

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BattleServiceClient interface {
	// 試合の初期登録
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*GameDataResponse, error)
	// 現在の試合情報の取得
	GetGameData(ctx context.Context, in *GetGameDataRequest, opts ...grpc.CallOption) (*GameDataResponse, error)
	RegisterCharacters(ctx context.Context, in *RegisterCharactersRequest, opts ...grpc.CallOption) (*RegisterCharactersResponse, error)
	// 対戦中のアクション同期（双方向ストリーミング）
	// 片方が動かしたら、もう片方に最新の GameDataResponse を流す
	StreamGame(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PlayerAction, GameDataResponse], error)
}

type battleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleServiceClient(cc grpc.ClientConnInterface) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*GameDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDataResponse)
	err := c.cc.Invoke(ctx, BattleService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) GetGameData(ctx context.Context, in *GetGameDataRequest, opts ...grpc.CallOption) (*GameDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDataResponse)
	err := c.cc.Invoke(ctx, BattleService_GetGameData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) RegisterCharacters(ctx context.Context, in *RegisterCharactersRequest, opts ...grpc.CallOption) (*RegisterCharactersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCharactersResponse)
	err := c.cc.Invoke(ctx, BattleService_RegisterCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) StreamGame(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PlayerAction, GameDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BattleService_ServiceDesc.Streams[0], BattleService_StreamGame_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PlayerAction, GameDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleService_StreamGameClient = grpc.BidiStreamingClient[PlayerAction, GameDataResponse]

// BattleServiceServer is the server API for BattleService service.
// All implementations must embed UnimplementedBattleServiceServer
// for forward compatibility.
type BattleServiceServer interface {
	// 試合の初期登録
	CreateGame(context.Context, *CreateGameRequest) (*GameDataResponse, error)
	// 現在の試合情報の取得
	GetGameData(context.Context, *GetGameDataRequest) (*GameDataResponse, error)
	RegisterCharacters(context.Context, *RegisterCharactersRequest) (*RegisterCharactersResponse, error)
	// 対戦中のアクション同期（双方向ストリーミング）
	// 片方が動かしたら、もう片方に最新の GameDataResponse を流す
	StreamGame(grpc.BidiStreamingServer[PlayerAction, GameDataResponse]) error
	mustEmbedUnimplementedBattleServiceServer()
}

// UnimplementedBattleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleServiceServer struct{}

func (UnimplementedBattleServiceServer) CreateGame(context.Context, *CreateGameRequest) (*GameDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedBattleServiceServer) GetGameData(context.Context, *GetGameDataRequest) (*GameDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameData not implemented")
}
func (UnimplementedBattleServiceServer) RegisterCharacters(context.Context, *RegisterCharactersRequest) (*RegisterCharactersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCharacters not implemented")
}
func (UnimplementedBattleServiceServer) StreamGame(grpc.BidiStreamingServer[PlayerAction, GameDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamGame not implemented")
}
func (UnimplementedBattleServiceServer) mustEmbedUnimplementedBattleServiceServer() {}
func (UnimplementedBattleServiceServer) testEmbeddedByValue()                       {}

// UnsafeBattleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleServiceServer will
// result in compilation errors.
type UnsafeBattleServiceServer interface {
	mustEmbedUnimplementedBattleServiceServer()
}

func RegisterBattleServiceServer(s grpc.ServiceRegistrar, srv BattleServiceServer) {
	// If the following call panics, it indicates UnimplementedBattleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleService_ServiceDesc, srv)
}

func _BattleService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_GetGameData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).GetGameData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_GetGameData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).GetGameData(ctx, req.(*GetGameDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_RegisterCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCharactersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).RegisterCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_RegisterCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).RegisterCharacters(ctx, req.(*RegisterCharactersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_StreamGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BattleServiceServer).StreamGame(&grpc.GenericServerStream[PlayerAction, GameDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleService_StreamGameServer = grpc.BidiStreamingServer[PlayerAction, GameDataResponse]

// BattleService_ServiceDesc is the grpc.ServiceDesc for BattleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.network.BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _BattleService_CreateGame_Handler,
		},
		{
			MethodName: "GetGameData",
			Handler:    _BattleService_GetGameData_Handler,
		},
		{
			MethodName: "RegisterCharacters",
			Handler:    _BattleService_RegisterCharacters_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGame",
			Handler:       _BattleService_StreamGame_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/game.proto",
}
