// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: v2/gameV2.proto

package pbv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_v2_gameV2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_v2_gameV2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_v2_gameV2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type DefinitionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DefinitionsJson string                 `protobuf:"bytes,1,opt,name=definitions_json,json=definitionsJson,proto3" json:"definitions_json,omitempty"`
	RulesVersion    string                 `protobuf:"bytes,2,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DefinitionsResponse) Reset() {
	*x = DefinitionsResponse{}
	mi := &file_v2_gameV2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefinitionsResponse) ProtoMessage() {}

func (x *DefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefinitionsResponse.ProtoReflect.Descriptor instead.
func (*DefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{3}
}

func (x *DefinitionsResponse) GetDefinitionsJson() string {
	if x != nil {
		return x.DefinitionsJson
	}
	return ""
}

func (x *DefinitionsResponse) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_v2_gameV2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGameRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type GameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRequest) Reset() {
	*x = GameRequest{}
	mi := &file_v2_gameV2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRequest) ProtoMessage() {}

func (x *GameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRequest.ProtoReflect.Descriptor instead.
func (*GameRequest) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{5}
}

func (x *GameRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type SelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	DefinitionIds []string               `protobuf:"bytes,2,rep,name=definition_ids,json=definitionIds,proto3" json:"definition_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectionRequest) Reset() {
	*x = SelectionRequest{}
	mi := &file_v2_gameV2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionRequest) ProtoMessage() {}

func (x *SelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionRequest.ProtoReflect.Descriptor instead.
func (*SelectionRequest) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{6}
}

func (x *SelectionRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *SelectionRequest) GetDefinitionIds() []string {
	if x != nil {
		return x.DefinitionIds
	}
	return nil
}

type ActionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MatchId          string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	CommandId        string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	CharacterId      string                 `protobuf:"bytes,4,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	AttackIndex      int32                  `protobuf:"varint,5,opt,name=attack_index,json=attackIndex,proto3" json:"attack_index,omitempty"`
	Target           *Position              `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Direction        *Position              `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_v2_gameV2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{7}
}

func (x *ActionRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ActionRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ActionRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ActionRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *ActionRequest) GetAttackIndex() int32 {
	if x != nil {
		return x.AttackIndex
	}
	return 0
}

func (x *ActionRequest) GetTarget() *Position {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ActionRequest) GetDirection() *Position {
	if x != nil {
		return x.Direction
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_v2_gameV2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{8}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cost          int32                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_v2_gameV2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{9}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Hp            int32                  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,3,opt,name=max_hp,json=maxHP,proto3" json:"max_hp,omitempty"`
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_v2_gameV2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{10}
}

func (x *Base) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Base) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Base) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Base) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Character struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DefinitionId   string                 `protobuf:"bytes,2,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	OwnerId        string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Hp             int32                  `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp          int32                  `protobuf:"varint,6,opt,name=max_hp,json=maxHP,proto3" json:"max_hp,omitempty"`
	Position       *Position              `protobuf:"bytes,7,opt,name=position,proto3" json:"position,omitempty"`
	Effects        []string               `protobuf:"bytes,8,rep,name=effects,proto3" json:"effects,omitempty"`
	ReviveUsed     bool                   `protobuf:"varint,9,opt,name=revive_used,json=reviveUsed,proto3" json:"revive_used,omitempty"`
	DepartureUsed  bool                   `protobuf:"varint,10,opt,name=departure_used,json=departureUsed,proto3" json:"departure_used,omitempty"`
	DrankTurn      int32                  `protobuf:"varint,11,opt,name=drank_turn,json=drankTurn,proto3" json:"drank_turn,omitempty"`
	HangoverTurn   int32                  `protobuf:"varint,12,opt,name=hangover_turn,json=hangoverTurn,proto3" json:"hangover_turn,omitempty"`
	HangoverUntil  int32                  `protobuf:"varint,13,opt,name=hangover_until,json=hangoverUntil,proto3" json:"hangover_until,omitempty"`
	UsedSkills     map[string]int32       `protobuf:"bytes,14,rep,name=used_skills,json=usedSkills,proto3" json:"used_skills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CombatStance   bool                   `protobuf:"varint,15,opt,name=combat_stance,json=combatStance,proto3" json:"combat_stance,omitempty"`
	BarrierTurn    int32                  `protobuf:"varint,16,opt,name=barrier_turn,json=barrierTurn,proto3" json:"barrier_turn,omitempty"`
	Wriggling      bool                   `protobuf:"varint,17,opt,name=wriggling,proto3" json:"wriggling,omitempty"`
	TemporaryBuffs []string               `protobuf:"bytes,18,rep,name=temporary_buffs,json=temporaryBuffs,proto3" json:"temporary_buffs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_v2_gameV2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{11}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *Character) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Character) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Character) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Character) GetEffects() []string {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *Character) GetReviveUsed() bool {
	if x != nil {
		return x.ReviveUsed
	}
	return false
}

func (x *Character) GetDepartureUsed() bool {
	if x != nil {
		return x.DepartureUsed
	}
	return false
}

func (x *Character) GetDrankTurn() int32 {
	if x != nil {
		return x.DrankTurn
	}
	return 0
}

func (x *Character) GetHangoverTurn() int32 {
	if x != nil {
		return x.HangoverTurn
	}
	return 0
}

func (x *Character) GetHangoverUntil() int32 {
	if x != nil {
		return x.HangoverUntil
	}
	return 0
}

func (x *Character) GetUsedSkills() map[string]int32 {
	if x != nil {
		return x.UsedSkills
	}
	return nil
}

func (x *Character) GetCombatStance() bool {
	if x != nil {
		return x.CombatStance
	}
	return false
}

func (x *Character) GetBarrierTurn() int32 {
	if x != nil {
		return x.BarrierTurn
	}
	return 0
}

func (x *Character) GetWriggling() bool {
	if x != nil {
		return x.Wriggling
	}
	return false
}

func (x *Character) GetTemporaryBuffs() []string {
	if x != nil {
		return x.TemporaryBuffs
	}
	return nil
}

type TileEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Hp            int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TileEffect) Reset() {
	*x = TileEffect{}
	mi := &file_v2_gameV2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TileEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileEffect) ProtoMessage() {}

func (x *TileEffect) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileEffect.ProtoReflect.Descriptor instead.
func (*TileEffect) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{12}
}

func (x *TileEffect) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *TileEffect) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TileEffect) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *TileEffect) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_v2_gameV2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{13}
}

func (x *Event) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type State struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MatchId        string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Revision       uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Started        bool                   `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	ReadyPlayerIds []string               `protobuf:"bytes,4,rep,name=ready_player_ids,json=readyPlayerIds,proto3" json:"ready_player_ids,omitempty"`
	Players        []*Player              `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	Bases          []*Base                `protobuf:"bytes,6,rep,name=bases,proto3" json:"bases,omitempty"`
	Characters     []*Character           `protobuf:"bytes,7,rep,name=characters,proto3" json:"characters,omitempty"`
	TileEffects    []*TileEffect          `protobuf:"bytes,8,rep,name=tile_effects,json=tileEffects,proto3" json:"tile_effects,omitempty"`
	BlockedCells   []*Position            `protobuf:"bytes,9,rep,name=blocked_cells,json=blockedCells,proto3" json:"blocked_cells,omitempty"`
	TurnPlayerId   string                 `protobuf:"bytes,10,opt,name=turn_player_id,json=turnPlayerId,proto3" json:"turn_player_id,omitempty"`
	Turn           int32                  `protobuf:"varint,11,opt,name=turn,proto3" json:"turn,omitempty"`
	Phase          string                 `protobuf:"bytes,12,opt,name=phase,proto3" json:"phase,omitempty"`
	PhaseDeadline  string                 `protobuf:"bytes,13,opt,name=phase_deadline,json=phaseDeadline,proto3" json:"phase_deadline,omitempty"`
	TurnDeadline   string                 `protobuf:"bytes,14,opt,name=turn_deadline,json=turnDeadline,proto3" json:"turn_deadline,omitempty"`
	ServerTime     string                 `protobuf:"bytes,15,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	WinnerId       string                 `protobuf:"bytes,16,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	Finished       bool                   `protobuf:"varint,17,opt,name=finished,proto3" json:"finished,omitempty"`
	LastEvent      *Event                 `protobuf:"bytes,18,opt,name=last_event,json=lastEvent,proto3" json:"last_event,omitempty"`
	Events         []*Event               `protobuf:"bytes,19,rep,name=events,proto3" json:"events,omitempty"`
	TestOwnerId    string                 `protobuf:"bytes,20,opt,name=test_owner_id,json=testOwnerId,proto3" json:"test_owner_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_v2_gameV2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{14}
}

func (x *State) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *State) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *State) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *State) GetReadyPlayerIds() []string {
	if x != nil {
		return x.ReadyPlayerIds
	}
	return nil
}

func (x *State) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *State) GetBases() []*Base {
	if x != nil {
		return x.Bases
	}
	return nil
}

func (x *State) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *State) GetTileEffects() []*TileEffect {
	if x != nil {
		return x.TileEffects
	}
	return nil
}

func (x *State) GetBlockedCells() []*Position {
	if x != nil {
		return x.BlockedCells
	}
	return nil
}

func (x *State) GetTurnPlayerId() string {
	if x != nil {
		return x.TurnPlayerId
	}
	return ""
}

func (x *State) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *State) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *State) GetPhaseDeadline() string {
	if x != nil {
		return x.PhaseDeadline
	}
	return ""
}

func (x *State) GetTurnDeadline() string {
	if x != nil {
		return x.TurnDeadline
	}
	return ""
}

func (x *State) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *State) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *State) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *State) GetLastEvent() *Event {
	if x != nil {
		return x.LastEvent
	}
	return nil
}

func (x *State) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *State) GetTestOwnerId() string {
	if x != nil {
		return x.TestOwnerId
	}
	return ""
}

type Snapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoomId            uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	State             *State                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	LastLogSequence   uint64                 `protobuf:"varint,3,opt,name=last_log_sequence,json=lastLogSequence,proto3" json:"last_log_sequence,omitempty"`
	SelectedPlayerIds []string               `protobuf:"bytes,4,rep,name=selected_player_ids,json=selectedPlayerIds,proto3" json:"selected_player_ids,omitempty"`
	P1Rate            int32                  `protobuf:"varint,5,opt,name=p1_rate,json=p1Rate,proto3" json:"p1_rate,omitempty"`
	P2Rate            int32                  `protobuf:"varint,6,opt,name=p2_rate,json=p2Rate,proto3" json:"p2_rate,omitempty"`
	P1RateDelta       int32                  `protobuf:"varint,7,opt,name=p1_rate_delta,json=p1RateDelta,proto3" json:"p1_rate_delta,omitempty"`
	P2RateDelta       int32                  `protobuf:"varint,8,opt,name=p2_rate_delta,json=p2RateDelta,proto3" json:"p2_rate_delta,omitempty"`
	RulesVersion      string                 `protobuf:"bytes,9,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_v2_gameV2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{15}
}

func (x *Snapshot) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Snapshot) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Snapshot) GetLastLogSequence() uint64 {
	if x != nil {
		return x.LastLogSequence
	}
	return 0
}

func (x *Snapshot) GetSelectedPlayerIds() []string {
	if x != nil {
		return x.SelectedPlayerIds
	}
	return nil
}

func (x *Snapshot) GetP1Rate() int32 {
	if x != nil {
		return x.P1Rate
	}
	return 0
}

func (x *Snapshot) GetP2Rate() int32 {
	if x != nil {
		return x.P2Rate
	}
	return 0
}

func (x *Snapshot) GetP1RateDelta() int32 {
	if x != nil {
		return x.P1RateDelta
	}
	return 0
}

func (x *Snapshot) GetP2RateDelta() int32 {
	if x != nil {
		return x.P2RateDelta
	}
	return 0
}

func (x *Snapshot) GetRulesVersion() string {
	if x != nil {
		return x.RulesVersion
	}
	return ""
}

// Each durable transition has full before/after state for exact animation/recovery.
// This sequence is independent of State.revision (one action may emit several events).
type ActionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Command       *ActionRequest         `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Before        *State                 `protobuf:"bytes,5,opt,name=before,proto3" json:"before,omitempty"`
	After         *State                 `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionLog) Reset() {
	*x = ActionLog{}
	mi := &file_v2_gameV2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionLog) ProtoMessage() {}

func (x *ActionLog) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionLog.ProtoReflect.Descriptor instead.
func (*ActionLog) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{16}
}

func (x *ActionLog) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ActionLog) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ActionLog) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionLog) GetCommand() *ActionRequest {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ActionLog) GetBefore() *State {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ActionLog) GetAfter() *State {
	if x != nil {
		return x.After
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	AfterSequence uint64                 `protobuf:"varint,2,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_v2_gameV2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{17}
}

func (x *LogRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *LogRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *LogRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*ActionLog           `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	NextSequence  uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_v2_gameV2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_gameV2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_v2_gameV2_proto_rawDescGZIP(), []int{18}
}

func (x *LogResponse) GetLogs() []*ActionLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *LogResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

var File_v2_gameV2_proto protoreflect.FileDescriptor

const file_v2_gameV2_proto_rawDesc = "" +
	"\n" +
	"\x0fv2/gameV2.proto\x12\x0fgame.network.v2\"\a\n" +
	"\x05Empty\">\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"a\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"e\n" +
	"\x13DefinitionsResponse\x12)\n" +
	"\x10definitions_json\x18\x01 \x01(\tR\x0fdefinitionsJson\x12#\n" +
	"\rrules_version\x18\x02 \x01(\tR\frulesVersion\",\n" +
	"\x11CreateGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\"(\n" +
	"\vGameRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"T\n" +
	"\x10SelectionRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12%\n" +
	"\x0edefinition_ids\x18\x02 \x03(\tR\rdefinitionIds\"\xa8\x02\n" +
	"\rActionRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\x12!\n" +
	"\fcharacter_id\x18\x04 \x01(\tR\vcharacterId\x12!\n" +
	"\fattack_index\x18\x05 \x01(\x05R\vattackIndex\x121\n" +
	"\x06target\x18\x06 \x01(\v2\x19.game.network.v2.PositionR\x06target\x127\n" +
	"\tdirection\x18\a \x01(\v2\x19.game.network.v2.PositionR\tdirection\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"@\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x05R\x04cost\"\x7f\n" +
	"\x04Base\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x03 \x01(\x05R\x05maxHP\x125\n" +
	"\bposition\x18\x04 \x01(\v2\x19.game.network.v2.PositionR\bposition\"\xb5\x05\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdefinition_id\x18\x02 \x01(\tR\fdefinitionId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x05 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x06 \x01(\x05R\x05maxHP\x125\n" +
	"\bposition\x18\a \x01(\v2\x19.game.network.v2.PositionR\bposition\x12\x18\n" +
	"\aeffects\x18\b \x03(\tR\aeffects\x12\x1f\n" +
	"\vrevive_used\x18\t \x01(\bR\n" +
	"reviveUsed\x12%\n" +
	"\x0edeparture_used\x18\n" +
	" \x01(\bR\rdepartureUsed\x12\x1d\n" +
	"\n" +
	"drank_turn\x18\v \x01(\x05R\tdrankTurn\x12#\n" +
	"\rhangover_turn\x18\f \x01(\x05R\fhangoverTurn\x12%\n" +
	"\x0ehangover_until\x18\r \x01(\x05R\rhangoverUntil\x12K\n" +
	"\vused_skills\x18\x0e \x03(\v2*.game.network.v2.Character.UsedSkillsEntryR\n" +
	"usedSkills\x12#\n" +
	"\rcombat_stance\x18\x0f \x01(\bR\fcombatStance\x12!\n" +
	"\fbarrier_turn\x18\x10 \x01(\x05R\vbarrierTurn\x12\x1c\n" +
	"\twriggling\x18\x11 \x01(\bR\twriggling\x12'\n" +
	"\x0ftemporary_buffs\x18\x12 \x03(\tR\x0etemporaryBuffs\x1a=\n" +
	"\x0fUsedSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x82\x01\n" +
	"\n" +
	"TileEffect\x125\n" +
	"\bposition\x18\x01 \x01(\v2\x19.game.network.v2.PositionR\bposition\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\"K\n" +
	"\x05Event\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x9f\x06\n" +
	"\x05State\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x18\n" +
	"\astarted\x18\x03 \x01(\bR\astarted\x12(\n" +
	"\x10ready_player_ids\x18\x04 \x03(\tR\x0ereadyPlayerIds\x121\n" +
	"\aplayers\x18\x05 \x03(\v2\x17.game.network.v2.PlayerR\aplayers\x12+\n" +
	"\x05bases\x18\x06 \x03(\v2\x15.game.network.v2.BaseR\x05bases\x12:\n" +
	"\n" +
	"characters\x18\a \x03(\v2\x1a.game.network.v2.CharacterR\n" +
	"characters\x12>\n" +
	"\ftile_effects\x18\b \x03(\v2\x1b.game.network.v2.TileEffectR\vtileEffects\x12>\n" +
	"\rblocked_cells\x18\t \x03(\v2\x19.game.network.v2.PositionR\fblockedCells\x12$\n" +
	"\x0eturn_player_id\x18\n" +
	" \x01(\tR\fturnPlayerId\x12\x12\n" +
	"\x04turn\x18\v \x01(\x05R\x04turn\x12\x14\n" +
	"\x05phase\x18\f \x01(\tR\x05phase\x12%\n" +
	"\x0ephase_deadline\x18\r \x01(\tR\rphaseDeadline\x12#\n" +
	"\rturn_deadline\x18\x0e \x01(\tR\fturnDeadline\x12\x1f\n" +
	"\vserver_time\x18\x0f \x01(\tR\n" +
	"serverTime\x12\x1b\n" +
	"\twinner_id\x18\x10 \x01(\tR\bwinnerId\x12\x1a\n" +
	"\bfinished\x18\x11 \x01(\bR\bfinished\x125\n" +
	"\n" +
	"last_event\x18\x12 \x01(\v2\x16.game.network.v2.EventR\tlastEvent\x12.\n" +
	"\x06events\x18\x13 \x03(\v2\x16.game.network.v2.EventR\x06events\x12\"\n" +
	"\rtest_owner_id\x18\x14 \x01(\tR\vtestOwnerId\"\xcc\x02\n" +
	"\bSnapshot\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12,\n" +
	"\x05state\x18\x02 \x01(\v2\x16.game.network.v2.StateR\x05state\x12*\n" +
	"\x11last_log_sequence\x18\x03 \x01(\x04R\x0flastLogSequence\x12.\n" +
	"\x13selected_player_ids\x18\x04 \x03(\tR\x11selectedPlayerIds\x12\x17\n" +
	"\ap1_rate\x18\x05 \x01(\x05R\x06p1Rate\x12\x17\n" +
	"\ap2_rate\x18\x06 \x01(\x05R\x06p2Rate\x12\"\n" +
	"\rp1_rate_delta\x18\a \x01(\x05R\vp1RateDelta\x12\"\n" +
	"\rp2_rate_delta\x18\b \x01(\x05R\vp2RateDelta\x12#\n" +
	"\rrules_version\x18\t \x01(\tR\frulesVersion\"\xfd\x01\n" +
	"\tActionLog\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x128\n" +
	"\acommand\x18\x04 \x01(\v2\x1e.game.network.v2.ActionRequestR\acommand\x12.\n" +
	"\x06before\x18\x05 \x01(\v2\x16.game.network.v2.StateR\x06before\x12,\n" +
	"\x05after\x18\x06 \x01(\v2\x16.game.network.v2.StateR\x05after\"d\n" +
	"\n" +
	"LogRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12%\n" +
	"\x0eafter_sequence\x18\x02 \x01(\x04R\rafterSequence\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"b\n" +
	"\vLogResponse\x12.\n" +
	"\x04logs\x18\x01 \x03(\v2\x1a.game.network.v2.ActionLogR\x04logs\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence2\x9f\b\n" +
	"\x0fBattleServiceV2\x12F\n" +
	"\x05Login\x12\x1d.game.network.v2.LoginRequest\x1a\x1e.game.network.v2.LoginResponse\x12N\n" +
	"\x0eGetDefinitions\x12\x16.game.network.v2.Empty\x1a$.game.network.v2.DefinitionsResponse\x12K\n" +
	"\n" +
	"CreateGame\x12\".game.network.v2.CreateGameRequest\x1a\x19.game.network.v2.Snapshot\x12L\n" +
	"\vGetRoomGame\x12\".game.network.v2.CreateGameRequest\x1a\x19.game.network.v2.Snapshot\x12R\n" +
	"\x12RegisterCharacters\x12!.game.network.v2.SelectionRequest\x1a\x19.game.network.v2.Snapshot\x12@\n" +
	"\x05Ready\x12\x1c.game.network.v2.GameRequest\x1a\x19.game.network.v2.Snapshot\x12E\n" +
	"\n" +
	"CancelGame\x12\x1c.game.network.v2.GameRequest\x1a\x19.game.network.v2.Snapshot\x12F\n" +
	"\vGetGameData\x12\x1c.game.network.v2.GameRequest\x1a\x19.game.network.v2.Snapshot\x12G\n" +
	"\n" +
	"StreamGame\x12\x1c.game.network.v2.GameRequest\x1a\x19.game.network.v2.Snapshot0\x01\x12F\n" +
	"\tApplyMove\x12\x1e.game.network.v2.ActionRequest\x1a\x19.game.network.v2.Snapshot\x12H\n" +
	"\vApplyAttack\x12\x1e.game.network.v2.ActionRequest\x1a\x19.game.network.v2.Snapshot\x12D\n" +
	"\aEndTurn\x12\x1e.game.network.v2.ActionRequest\x1a\x19.game.network.v2.Snapshot\x12F\n" +
	"\tSurrender\x12\x1e.game.network.v2.ActionRequest\x1a\x19.game.network.v2.Snapshot\x12K\n" +
	"\x0eFetchActionLog\x12\x1b.game.network.v2.LogRequest\x1a\x1c.game.network.v2.LogResponseB&Z\x12auxilia/pb/v2;pbv2\xaa\x02\x0fGame.Network.V2b\x06proto3"

var (
	file_v2_gameV2_proto_rawDescOnce sync.Once
	file_v2_gameV2_proto_rawDescData []byte
)

func file_v2_gameV2_proto_rawDescGZIP() []byte {
	file_v2_gameV2_proto_rawDescOnce.Do(func() {
		file_v2_gameV2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_gameV2_proto_rawDesc), len(file_v2_gameV2_proto_rawDesc)))
	})
	return file_v2_gameV2_proto_rawDescData
}

var file_v2_gameV2_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_v2_gameV2_proto_goTypes = []any{
	(*Empty)(nil),               // 0: game.network.v2.Empty
	(*LoginRequest)(nil),        // 1: game.network.v2.LoginRequest
	(*LoginResponse)(nil),       // 2: game.network.v2.LoginResponse
	(*DefinitionsResponse)(nil), // 3: game.network.v2.DefinitionsResponse
	(*CreateGameRequest)(nil),   // 4: game.network.v2.CreateGameRequest
	(*GameRequest)(nil),         // 5: game.network.v2.GameRequest
	(*SelectionRequest)(nil),    // 6: game.network.v2.SelectionRequest
	(*ActionRequest)(nil),       // 7: game.network.v2.ActionRequest
	(*Position)(nil),            // 8: game.network.v2.Position
	(*Player)(nil),              // 9: game.network.v2.Player
	(*Base)(nil),                // 10: game.network.v2.Base
	(*Character)(nil),           // 11: game.network.v2.Character
	(*TileEffect)(nil),          // 12: game.network.v2.TileEffect
	(*Event)(nil),               // 13: game.network.v2.Event
	(*State)(nil),               // 14: game.network.v2.State
	(*Snapshot)(nil),            // 15: game.network.v2.Snapshot
	(*ActionLog)(nil),           // 16: game.network.v2.ActionLog
	(*LogRequest)(nil),          // 17: game.network.v2.LogRequest
	(*LogResponse)(nil),         // 18: game.network.v2.LogResponse
	nil,                         // 19: game.network.v2.Character.UsedSkillsEntry
}
var file_v2_gameV2_proto_depIdxs = []int32{
	8,  // 0: game.network.v2.ActionRequest.target:type_name -> game.network.v2.Position
	8,  // 1: game.network.v2.ActionRequest.direction:type_name -> game.network.v2.Position
	8,  // 2: game.network.v2.Base.position:type_name -> game.network.v2.Position
	8,  // 3: game.network.v2.Character.position:type_name -> game.network.v2.Position
	19, // 4: game.network.v2.Character.used_skills:type_name -> game.network.v2.Character.UsedSkillsEntry
	8,  // 5: game.network.v2.TileEffect.position:type_name -> game.network.v2.Position
	9,  // 6: game.network.v2.State.players:type_name -> game.network.v2.Player
	10, // 7: game.network.v2.State.bases:type_name -> game.network.v2.Base
	11, // 8: game.network.v2.State.characters:type_name -> game.network.v2.Character
	12, // 9: game.network.v2.State.tile_effects:type_name -> game.network.v2.TileEffect
	8,  // 10: game.network.v2.State.blocked_cells:type_name -> game.network.v2.Position
	13, // 11: game.network.v2.State.last_event:type_name -> game.network.v2.Event
	13, // 12: game.network.v2.State.events:type_name -> game.network.v2.Event
	14, // 13: game.network.v2.Snapshot.state:type_name -> game.network.v2.State
	7,  // 14: game.network.v2.ActionLog.command:type_name -> game.network.v2.ActionRequest
	14, // 15: game.network.v2.ActionLog.before:type_name -> game.network.v2.State
	14, // 16: game.network.v2.ActionLog.after:type_name -> game.network.v2.State
	16, // 17: game.network.v2.LogResponse.logs:type_name -> game.network.v2.ActionLog
	1,  // 18: game.network.v2.BattleServiceV2.Login:input_type -> game.network.v2.LoginRequest
	0,  // 19: game.network.v2.BattleServiceV2.GetDefinitions:input_type -> game.network.v2.Empty
	4,  // 20: game.network.v2.BattleServiceV2.CreateGame:input_type -> game.network.v2.CreateGameRequest
	4,  // 21: game.network.v2.BattleServiceV2.GetRoomGame:input_type -> game.network.v2.CreateGameRequest
	6,  // 22: game.network.v2.BattleServiceV2.RegisterCharacters:input_type -> game.network.v2.SelectionRequest
	5,  // 23: game.network.v2.BattleServiceV2.Ready:input_type -> game.network.v2.GameRequest
	5,  // 24: game.network.v2.BattleServiceV2.CancelGame:input_type -> game.network.v2.GameRequest
	5,  // 25: game.network.v2.BattleServiceV2.GetGameData:input_type -> game.network.v2.GameRequest
	5,  // 26: game.network.v2.BattleServiceV2.StreamGame:input_type -> game.network.v2.GameRequest
	7,  // 27: game.network.v2.BattleServiceV2.ApplyMove:input_type -> game.network.v2.ActionRequest
	7,  // 28: game.network.v2.BattleServiceV2.ApplyAttack:input_type -> game.network.v2.ActionRequest
	7,  // 29: game.network.v2.BattleServiceV2.EndTurn:input_type -> game.network.v2.ActionRequest
	7,  // 30: game.network.v2.BattleServiceV2.Surrender:input_type -> game.network.v2.ActionRequest
	17, // 31: game.network.v2.BattleServiceV2.FetchActionLog:input_type -> game.network.v2.LogRequest
	2,  // 32: game.network.v2.BattleServiceV2.Login:output_type -> game.network.v2.LoginResponse
	3,  // 33: game.network.v2.BattleServiceV2.GetDefinitions:output_type -> game.network.v2.DefinitionsResponse
	15, // 34: game.network.v2.BattleServiceV2.CreateGame:output_type -> game.network.v2.Snapshot
	15, // 35: game.network.v2.BattleServiceV2.GetRoomGame:output_type -> game.network.v2.Snapshot
	15, // 36: game.network.v2.BattleServiceV2.RegisterCharacters:output_type -> game.network.v2.Snapshot
	15, // 37: game.network.v2.BattleServiceV2.Ready:output_type -> game.network.v2.Snapshot
	15, // 38: game.network.v2.BattleServiceV2.CancelGame:output_type -> game.network.v2.Snapshot
	15, // 39: game.network.v2.BattleServiceV2.GetGameData:output_type -> game.network.v2.Snapshot
	15, // 40: game.network.v2.BattleServiceV2.StreamGame:output_type -> game.network.v2.Snapshot
	15, // 41: game.network.v2.BattleServiceV2.ApplyMove:output_type -> game.network.v2.Snapshot
	15, // 42: game.network.v2.BattleServiceV2.ApplyAttack:output_type -> game.network.v2.Snapshot
	15, // 43: game.network.v2.BattleServiceV2.EndTurn:output_type -> game.network.v2.Snapshot
	15, // 44: game.network.v2.BattleServiceV2.Surrender:output_type -> game.network.v2.Snapshot
	18, // 45: game.network.v2.BattleServiceV2.FetchActionLog:output_type -> game.network.v2.LogResponse
	32, // [32:46] is the sub-list for method output_type
	18, // [18:32] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_v2_gameV2_proto_init() }
func file_v2_gameV2_proto_init() {
	if File_v2_gameV2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_gameV2_proto_rawDesc), len(file_v2_gameV2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_gameV2_proto_goTypes,
		DependencyIndexes: file_v2_gameV2_proto_depIdxs,
		MessageInfos:      file_v2_gameV2_proto_msgTypes,
	}.Build()
	File_v2_gameV2_proto = out.File
	file_v2_gameV2_proto_goTypes = nil
	file_v2_gameV2_proto_depIdxs = nil
}
