// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v2/gameV2.proto

package pbv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleServiceV2_Login_FullMethodName              = "/game.network.v2.BattleServiceV2/Login"
	BattleServiceV2_GetDefinitions_FullMethodName     = "/game.network.v2.BattleServiceV2/GetDefinitions"
	BattleServiceV2_CreateGame_FullMethodName         = "/game.network.v2.BattleServiceV2/CreateGame"
	BattleServiceV2_GetRoomGame_FullMethodName        = "/game.network.v2.BattleServiceV2/GetRoomGame"
	BattleServiceV2_RegisterCharacters_FullMethodName = "/game.network.v2.BattleServiceV2/RegisterCharacters"
	BattleServiceV2_Ready_FullMethodName              = "/game.network.v2.BattleServiceV2/Ready"
	BattleServiceV2_CancelGame_FullMethodName         = "/game.network.v2.BattleServiceV2/CancelGame"
	BattleServiceV2_GetGameData_FullMethodName        = "/game.network.v2.BattleServiceV2/GetGameData"
	BattleServiceV2_StreamGame_FullMethodName         = "/game.network.v2.BattleServiceV2/StreamGame"
	BattleServiceV2_ApplyMove_FullMethodName          = "/game.network.v2.BattleServiceV2/ApplyMove"
	BattleServiceV2_ApplyAttack_FullMethodName        = "/game.network.v2.BattleServiceV2/ApplyAttack"
	BattleServiceV2_EndTurn_FullMethodName            = "/game.network.v2.BattleServiceV2/EndTurn"
	BattleServiceV2_Surrender_FullMethodName          = "/game.network.v2.BattleServiceV2/Surrender"
	BattleServiceV2_FetchActionLog_FullMethodName     = "/game.network.v2.BattleServiceV2/FetchActionLog"
)

// BattleServiceV2Client is the client API for BattleServiceV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Send authorization: Bearer <token> as gRPC metadata after Login.
type BattleServiceV2Client interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetDefinitions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DefinitionsResponse, error)
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*Snapshot, error)
	GetRoomGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*Snapshot, error)
	RegisterCharacters(ctx context.Context, in *SelectionRequest, opts ...grpc.CallOption) (*Snapshot, error)
	Ready(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*Snapshot, error)
	CancelGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*Snapshot, error)
	GetGameData(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*Snapshot, error)
	StreamGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error)
	ApplyMove(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*Snapshot, error)
	ApplyAttack(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*Snapshot, error)
	EndTurn(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*Snapshot, error)
	Surrender(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*Snapshot, error)
	FetchActionLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type battleServiceV2Client struct {
	cc grpc.ClientConnInterface
}

func NewBattleServiceV2Client(cc grpc.ClientConnInterface) BattleServiceV2Client {
	return &battleServiceV2Client{cc}
}

func (c *battleServiceV2Client) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, BattleServiceV2_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) GetDefinitions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefinitionsResponse)
	err := c.cc.Invoke(ctx, BattleServiceV2_GetDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) GetRoomGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_GetRoomGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) RegisterCharacters(ctx context.Context, in *SelectionRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_RegisterCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) Ready(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) CancelGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_CancelGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) GetGameData(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_GetGameData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) StreamGame(ctx context.Context, in *GameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BattleServiceV2_ServiceDesc.Streams[0], BattleServiceV2_StreamGame_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GameRequest, Snapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleServiceV2_StreamGameClient = grpc.ServerStreamingClient[Snapshot]

func (c *battleServiceV2Client) ApplyMove(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_ApplyMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) ApplyAttack(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_ApplyAttack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) EndTurn(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_EndTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) Surrender(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, BattleServiceV2_Surrender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceV2Client) FetchActionLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, BattleServiceV2_FetchActionLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleServiceV2Server is the server API for BattleServiceV2 service.
// All implementations must embed UnimplementedBattleServiceV2Server
// for forward compatibility.
//
// Send authorization: Bearer <token> as gRPC metadata after Login.
type BattleServiceV2Server interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetDefinitions(context.Context, *Empty) (*DefinitionsResponse, error)
	CreateGame(context.Context, *CreateGameRequest) (*Snapshot, error)
	GetRoomGame(context.Context, *CreateGameRequest) (*Snapshot, error)
	RegisterCharacters(context.Context, *SelectionRequest) (*Snapshot, error)
	Ready(context.Context, *GameRequest) (*Snapshot, error)
	CancelGame(context.Context, *GameRequest) (*Snapshot, error)
	GetGameData(context.Context, *GameRequest) (*Snapshot, error)
	StreamGame(*GameRequest, grpc.ServerStreamingServer[Snapshot]) error
	ApplyMove(context.Context, *ActionRequest) (*Snapshot, error)
	ApplyAttack(context.Context, *ActionRequest) (*Snapshot, error)
	EndTurn(context.Context, *ActionRequest) (*Snapshot, error)
	Surrender(context.Context, *ActionRequest) (*Snapshot, error)
	FetchActionLog(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedBattleServiceV2Server()
}

// UnimplementedBattleServiceV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleServiceV2Server struct{}

func (UnimplementedBattleServiceV2Server) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBattleServiceV2Server) GetDefinitions(context.Context, *Empty) (*DefinitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefinitions not implemented")
}
func (UnimplementedBattleServiceV2Server) CreateGame(context.Context, *CreateGameRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedBattleServiceV2Server) GetRoomGame(context.Context, *CreateGameRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomGame not implemented")
}
func (UnimplementedBattleServiceV2Server) RegisterCharacters(context.Context, *SelectionRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterCharacters not implemented")
}
func (UnimplementedBattleServiceV2Server) Ready(context.Context, *GameRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedBattleServiceV2Server) CancelGame(context.Context, *GameRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelGame not implemented")
}
func (UnimplementedBattleServiceV2Server) GetGameData(context.Context, *GameRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameData not implemented")
}
func (UnimplementedBattleServiceV2Server) StreamGame(*GameRequest, grpc.ServerStreamingServer[Snapshot]) error {
	return status.Errorf(codes.Unimplemented, "method StreamGame not implemented")
}
func (UnimplementedBattleServiceV2Server) ApplyMove(context.Context, *ActionRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyMove not implemented")
}
func (UnimplementedBattleServiceV2Server) ApplyAttack(context.Context, *ActionRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyAttack not implemented")
}
func (UnimplementedBattleServiceV2Server) EndTurn(context.Context, *ActionRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTurn not implemented")
}
func (UnimplementedBattleServiceV2Server) Surrender(context.Context, *ActionRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Surrender not implemented")
}
func (UnimplementedBattleServiceV2Server) FetchActionLog(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchActionLog not implemented")
}
func (UnimplementedBattleServiceV2Server) mustEmbedUnimplementedBattleServiceV2Server() {}
func (UnimplementedBattleServiceV2Server) testEmbeddedByValue()                         {}

// UnsafeBattleServiceV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleServiceV2Server will
// result in compilation errors.
type UnsafeBattleServiceV2Server interface {
	mustEmbedUnimplementedBattleServiceV2Server()
}

func RegisterBattleServiceV2Server(s grpc.ServiceRegistrar, srv BattleServiceV2Server) {
	// If the following call pancis, it indicates UnimplementedBattleServiceV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleServiceV2_ServiceDesc, srv)
}

func _BattleServiceV2_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_GetDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).GetDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_GetDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).GetDefinitions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_GetRoomGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).GetRoomGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_GetRoomGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).GetRoomGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_RegisterCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).RegisterCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_RegisterCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).RegisterCharacters(ctx, req.(*SelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).Ready(ctx, req.(*GameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_CancelGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).CancelGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_CancelGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).CancelGame(ctx, req.(*GameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_GetGameData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).GetGameData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_GetGameData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).GetGameData(ctx, req.(*GameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_StreamGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BattleServiceV2Server).StreamGame(m, &grpc.GenericServerStream[GameRequest, Snapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleServiceV2_StreamGameServer = grpc.ServerStreamingServer[Snapshot]

func _BattleServiceV2_ApplyMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).ApplyMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_ApplyMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).ApplyMove(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_ApplyAttack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).ApplyAttack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_ApplyAttack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).ApplyAttack(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_EndTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).EndTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_EndTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).EndTurn(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_Surrender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).Surrender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_Surrender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).Surrender(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleServiceV2_FetchActionLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceV2Server).FetchActionLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleServiceV2_FetchActionLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceV2Server).FetchActionLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BattleServiceV2_ServiceDesc is the grpc.ServiceDesc for BattleServiceV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleServiceV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.network.v2.BattleServiceV2",
	HandlerType: (*BattleServiceV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _BattleServiceV2_Login_Handler,
		},
		{
			MethodName: "GetDefinitions",
			Handler:    _BattleServiceV2_GetDefinitions_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _BattleServiceV2_CreateGame_Handler,
		},
		{
			MethodName: "GetRoomGame",
			Handler:    _BattleServiceV2_GetRoomGame_Handler,
		},
		{
			MethodName: "RegisterCharacters",
			Handler:    _BattleServiceV2_RegisterCharacters_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _BattleServiceV2_Ready_Handler,
		},
		{
			MethodName: "CancelGame",
			Handler:    _BattleServiceV2_CancelGame_Handler,
		},
		{
			MethodName: "GetGameData",
			Handler:    _BattleServiceV2_GetGameData_Handler,
		},
		{
			MethodName: "ApplyMove",
			Handler:    _BattleServiceV2_ApplyMove_Handler,
		},
		{
			MethodName: "ApplyAttack",
			Handler:    _BattleServiceV2_ApplyAttack_Handler,
		},
		{
			MethodName: "EndTurn",
			Handler:    _BattleServiceV2_EndTurn_Handler,
		},
		{
			MethodName: "Surrender",
			Handler:    _BattleServiceV2_Surrender_Handler,
		},
		{
			MethodName: "FetchActionLog",
			Handler:    _BattleServiceV2_FetchActionLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGame",
			Handler:       _BattleServiceV2_StreamGame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v2/gameV2.proto",
}
