// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v2/roomV2.proto

package pbv2

import (
	pb "auxilia/pb"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomServiceV2_JoinRoom_FullMethodName        = "/game.network.v2.RoomServiceV2/JoinRoom"
	RoomServiceV2_LeaveRoom_FullMethodName       = "/game.network.v2.RoomServiceV2/LeaveRoom"
	RoomServiceV2_ListRoom_FullMethodName        = "/game.network.v2.RoomServiceV2/ListRoom"
	RoomServiceV2_EnterRing_FullMethodName       = "/game.network.v2.RoomServiceV2/EnterRing"
	RoomServiceV2_LeaveRing_FullMethodName       = "/game.network.v2.RoomServiceV2/LeaveRing"
	RoomServiceV2_SetReady_FullMethodName        = "/game.network.v2.RoomServiceV2/SetReady"
	RoomServiceV2_UpdateRoomState_FullMethodName = "/game.network.v2.RoomServiceV2/UpdateRoomState"
	RoomServiceV2_StartMatch_FullMethodName      = "/game.network.v2.RoomServiceV2/StartMatch"
	RoomServiceV2_StreamRoom_FullMethodName      = "/game.network.v2.RoomServiceV2/StreamRoom"
)

// RoomServiceV2Client is the client API for RoomServiceV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomServiceV2Client interface {
	JoinRoom(ctx context.Context, in *pb.JoinRoomRequest, opts ...grpc.CallOption) (*pb.JoinRoomResponse, error)
	LeaveRoom(ctx context.Context, in *pb.LeaveRoomRequest, opts ...grpc.CallOption) (*pb.LeaveRoomResponse, error)
	ListRoom(ctx context.Context, in *pb.ListRoomRequest, opts ...grpc.CallOption) (*pb.ListRoomResponse, error)
	EnterRing(ctx context.Context, in *pb.EnterRingRequest, opts ...grpc.CallOption) (*pb.EnterRingResponse, error)
	LeaveRing(ctx context.Context, in *pb.LeaveRingRequest, opts ...grpc.CallOption) (*pb.LeaveRingResponse, error)
	SetReady(ctx context.Context, in *pb.SetReadyRequest, opts ...grpc.CallOption) (*pb.SetReadyResponse, error)
	UpdateRoomState(ctx context.Context, in *pb.UpdateRoomStateRequest, opts ...grpc.CallOption) (*pb.UpdateRoomStateResponse, error)
	StartMatch(ctx context.Context, in *pb.StartMatchRequest, opts ...grpc.CallOption) (*pb.StartMatchResponse, error)
	// ルーム内のリアルタイム同期（入室時のStream接続用）
	StreamRoom(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb.RoomStreamRequest, pb.ListRoomResponse], error)
}

type roomServiceV2Client struct {
	cc grpc.ClientConnInterface
}

func NewRoomServiceV2Client(cc grpc.ClientConnInterface) RoomServiceV2Client {
	return &roomServiceV2Client{cc}
}

func (c *roomServiceV2Client) JoinRoom(ctx context.Context, in *pb.JoinRoomRequest, opts ...grpc.CallOption) (*pb.JoinRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.JoinRoomResponse)
	err := c.cc.Invoke(ctx, RoomServiceV2_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceV2Client) LeaveRoom(ctx context.Context, in *pb.LeaveRoomRequest, opts ...grpc.CallOption) (*pb.LeaveRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.LeaveRoomResponse)
	err := c.cc.Invoke(ctx, RoomServiceV2_LeaveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceV2Client) ListRoom(ctx context.Context, in *pb.ListRoomRequest, opts ...grpc.CallOption) (*pb.ListRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.ListRoomResponse)
	err := c.cc.Invoke(ctx, RoomServiceV2_ListRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceV2Client) EnterRing(ctx context.Context, in *pb.EnterRingRequest, opts ...grpc.CallOption) (*pb.EnterRingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.EnterRingResponse)
	err := c.cc.Invoke(ctx, RoomServiceV2_EnterRing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceV2Client) LeaveRing(ctx context.Context, in *pb.LeaveRingRequest, opts ...grpc.CallOption) (*pb.LeaveRingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.LeaveRingResponse)
	err := c.cc.Invoke(ctx, RoomServiceV2_LeaveRing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceV2Client) SetReady(ctx context.Context, in *pb.SetReadyRequest, opts ...grpc.CallOption) (*pb.SetReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.SetReadyResponse)
	err := c.cc.Invoke(ctx, RoomServiceV2_SetReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceV2Client) UpdateRoomState(ctx context.Context, in *pb.UpdateRoomStateRequest, opts ...grpc.CallOption) (*pb.UpdateRoomStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.UpdateRoomStateResponse)
	err := c.cc.Invoke(ctx, RoomServiceV2_UpdateRoomState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceV2Client) StartMatch(ctx context.Context, in *pb.StartMatchRequest, opts ...grpc.CallOption) (*pb.StartMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.StartMatchResponse)
	err := c.cc.Invoke(ctx, RoomServiceV2_StartMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceV2Client) StreamRoom(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb.RoomStreamRequest, pb.ListRoomResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RoomServiceV2_ServiceDesc.Streams[0], RoomServiceV2_StreamRoom_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.RoomStreamRequest, pb.ListRoomResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoomServiceV2_StreamRoomClient = grpc.BidiStreamingClient[pb.RoomStreamRequest, pb.ListRoomResponse]

// RoomServiceV2Server is the server API for RoomServiceV2 service.
// All implementations must embed UnimplementedRoomServiceV2Server
// for forward compatibility.
type RoomServiceV2Server interface {
	JoinRoom(context.Context, *pb.JoinRoomRequest) (*pb.JoinRoomResponse, error)
	LeaveRoom(context.Context, *pb.LeaveRoomRequest) (*pb.LeaveRoomResponse, error)
	ListRoom(context.Context, *pb.ListRoomRequest) (*pb.ListRoomResponse, error)
	EnterRing(context.Context, *pb.EnterRingRequest) (*pb.EnterRingResponse, error)
	LeaveRing(context.Context, *pb.LeaveRingRequest) (*pb.LeaveRingResponse, error)
	SetReady(context.Context, *pb.SetReadyRequest) (*pb.SetReadyResponse, error)
	UpdateRoomState(context.Context, *pb.UpdateRoomStateRequest) (*pb.UpdateRoomStateResponse, error)
	StartMatch(context.Context, *pb.StartMatchRequest) (*pb.StartMatchResponse, error)
	// ルーム内のリアルタイム同期（入室時のStream接続用）
	StreamRoom(grpc.BidiStreamingServer[pb.RoomStreamRequest, pb.ListRoomResponse]) error
	mustEmbedUnimplementedRoomServiceV2Server()
}

// UnimplementedRoomServiceV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomServiceV2Server struct{}

func (UnimplementedRoomServiceV2Server) JoinRoom(context.Context, *pb.JoinRoomRequest) (*pb.JoinRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedRoomServiceV2Server) LeaveRoom(context.Context, *pb.LeaveRoomRequest) (*pb.LeaveRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveRoom not implemented")
}
func (UnimplementedRoomServiceV2Server) ListRoom(context.Context, *pb.ListRoomRequest) (*pb.ListRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoom not implemented")
}
func (UnimplementedRoomServiceV2Server) EnterRing(context.Context, *pb.EnterRingRequest) (*pb.EnterRingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterRing not implemented")
}
func (UnimplementedRoomServiceV2Server) LeaveRing(context.Context, *pb.LeaveRingRequest) (*pb.LeaveRingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveRing not implemented")
}
func (UnimplementedRoomServiceV2Server) SetReady(context.Context, *pb.SetReadyRequest) (*pb.SetReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetReady not implemented")
}
func (UnimplementedRoomServiceV2Server) UpdateRoomState(context.Context, *pb.UpdateRoomStateRequest) (*pb.UpdateRoomStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoomState not implemented")
}
func (UnimplementedRoomServiceV2Server) StartMatch(context.Context, *pb.StartMatchRequest) (*pb.StartMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMatch not implemented")
}
func (UnimplementedRoomServiceV2Server) StreamRoom(grpc.BidiStreamingServer[pb.RoomStreamRequest, pb.ListRoomResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRoom not implemented")
}
func (UnimplementedRoomServiceV2Server) mustEmbedUnimplementedRoomServiceV2Server() {}
func (UnimplementedRoomServiceV2Server) testEmbeddedByValue()                       {}

// UnsafeRoomServiceV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomServiceV2Server will
// result in compilation errors.
type UnsafeRoomServiceV2Server interface {
	mustEmbedUnimplementedRoomServiceV2Server()
}

func RegisterRoomServiceV2Server(s grpc.ServiceRegistrar, srv RoomServiceV2Server) {
	// If the following call pancis, it indicates UnimplementedRoomServiceV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomServiceV2_ServiceDesc, srv)
}

func _RoomServiceV2_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceV2Server).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServiceV2_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceV2Server).JoinRoom(ctx, req.(*pb.JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomServiceV2_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.LeaveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceV2Server).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServiceV2_LeaveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceV2Server).LeaveRoom(ctx, req.(*pb.LeaveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomServiceV2_ListRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.ListRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceV2Server).ListRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServiceV2_ListRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceV2Server).ListRoom(ctx, req.(*pb.ListRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomServiceV2_EnterRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.EnterRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceV2Server).EnterRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServiceV2_EnterRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceV2Server).EnterRing(ctx, req.(*pb.EnterRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomServiceV2_LeaveRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.LeaveRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceV2Server).LeaveRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServiceV2_LeaveRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceV2Server).LeaveRing(ctx, req.(*pb.LeaveRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomServiceV2_SetReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.SetReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceV2Server).SetReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServiceV2_SetReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceV2Server).SetReady(ctx, req.(*pb.SetReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomServiceV2_UpdateRoomState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.UpdateRoomStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceV2Server).UpdateRoomState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServiceV2_UpdateRoomState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceV2Server).UpdateRoomState(ctx, req.(*pb.UpdateRoomStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomServiceV2_StartMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.StartMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceV2Server).StartMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServiceV2_StartMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceV2Server).StartMatch(ctx, req.(*pb.StartMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomServiceV2_StreamRoom_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoomServiceV2Server).StreamRoom(&grpc.GenericServerStream[pb.RoomStreamRequest, pb.ListRoomResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoomServiceV2_StreamRoomServer = grpc.BidiStreamingServer[pb.RoomStreamRequest, pb.ListRoomResponse]

// RoomServiceV2_ServiceDesc is the grpc.ServiceDesc for RoomServiceV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomServiceV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.network.v2.RoomServiceV2",
	HandlerType: (*RoomServiceV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinRoom",
			Handler:    _RoomServiceV2_JoinRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _RoomServiceV2_LeaveRoom_Handler,
		},
		{
			MethodName: "ListRoom",
			Handler:    _RoomServiceV2_ListRoom_Handler,
		},
		{
			MethodName: "EnterRing",
			Handler:    _RoomServiceV2_EnterRing_Handler,
		},
		{
			MethodName: "LeaveRing",
			Handler:    _RoomServiceV2_LeaveRing_Handler,
		},
		{
			MethodName: "SetReady",
			Handler:    _RoomServiceV2_SetReady_Handler,
		},
		{
			MethodName: "UpdateRoomState",
			Handler:    _RoomServiceV2_UpdateRoomState_Handler,
		},
		{
			MethodName: "StartMatch",
			Handler:    _RoomServiceV2_StartMatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRoom",
			Handler:       _RoomServiceV2_StreamRoom_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v2/roomV2.proto",
}
