// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: v2/roomV2.proto

package pbv2

import (
	pb "auxilia/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v2_roomV2_proto protoreflect.FileDescriptor

const file_v2_roomV2_proto_rawDesc = "" +
	"\n" +
	"\x0fv2/roomV2.proto\x12\x0fgame.network.v2\x1a\n" +
	"room.proto2\xce\x04\n" +
	"\rRoomServiceV2\x129\n" +
	"\bJoinRoom\x12\x15.room.JoinRoomRequest\x1a\x16.room.JoinRoomResponse\x12<\n" +
	"\tLeaveRoom\x12\x16.room.LeaveRoomRequest\x1a\x17.room.LeaveRoomResponse\x129\n" +
	"\bListRoom\x12\x15.room.ListRoomRequest\x1a\x16.room.ListRoomResponse\x12<\n" +
	"\tEnterRing\x12\x16.room.EnterRingRequest\x1a\x17.room.EnterRingResponse\x12<\n" +
	"\tLeaveRing\x12\x16.room.LeaveRingRequest\x1a\x17.room.LeaveRingResponse\x129\n" +
	"\bSetReady\x12\x15.room.SetReadyRequest\x1a\x16.room.SetReadyResponse\x12N\n" +
	"\x0fUpdateRoomState\x12\x1c.room.UpdateRoomStateRequest\x1a\x1d.room.UpdateRoomStateResponse\x12?\n" +
	"\n" +
	"StartMatch\x12\x17.room.StartMatchRequest\x1a\x18.room.StartMatchResponse\x12A\n" +
	"\n" +
	"StreamRoom\x12\x17.room.RoomStreamRequest\x1a\x16.room.ListRoomResponse(\x010\x01B&Z\x12auxilia/pb/v2;pbv2\xaa\x02\x0fGame.Network.V2b\x06proto3"

var file_v2_roomV2_proto_goTypes = []any{
	(*pb.JoinRoomRequest)(nil),         // 0: room.JoinRoomRequest
	(*pb.LeaveRoomRequest)(nil),        // 1: room.LeaveRoomRequest
	(*pb.ListRoomRequest)(nil),         // 2: room.ListRoomRequest
	(*pb.EnterRingRequest)(nil),        // 3: room.EnterRingRequest
	(*pb.LeaveRingRequest)(nil),        // 4: room.LeaveRingRequest
	(*pb.SetReadyRequest)(nil),         // 5: room.SetReadyRequest
	(*pb.UpdateRoomStateRequest)(nil),  // 6: room.UpdateRoomStateRequest
	(*pb.StartMatchRequest)(nil),       // 7: room.StartMatchRequest
	(*pb.RoomStreamRequest)(nil),       // 8: room.RoomStreamRequest
	(*pb.JoinRoomResponse)(nil),        // 9: room.JoinRoomResponse
	(*pb.LeaveRoomResponse)(nil),       // 10: room.LeaveRoomResponse
	(*pb.ListRoomResponse)(nil),        // 11: room.ListRoomResponse
	(*pb.EnterRingResponse)(nil),       // 12: room.EnterRingResponse
	(*pb.LeaveRingResponse)(nil),       // 13: room.LeaveRingResponse
	(*pb.SetReadyResponse)(nil),        // 14: room.SetReadyResponse
	(*pb.UpdateRoomStateResponse)(nil), // 15: room.UpdateRoomStateResponse
	(*pb.StartMatchResponse)(nil),      // 16: room.StartMatchResponse
}
var file_v2_roomV2_proto_depIdxs = []int32{
	0,  // 0: game.network.v2.RoomServiceV2.JoinRoom:input_type -> room.JoinRoomRequest
	1,  // 1: game.network.v2.RoomServiceV2.LeaveRoom:input_type -> room.LeaveRoomRequest
	2,  // 2: game.network.v2.RoomServiceV2.ListRoom:input_type -> room.ListRoomRequest
	3,  // 3: game.network.v2.RoomServiceV2.EnterRing:input_type -> room.EnterRingRequest
	4,  // 4: game.network.v2.RoomServiceV2.LeaveRing:input_type -> room.LeaveRingRequest
	5,  // 5: game.network.v2.RoomServiceV2.SetReady:input_type -> room.SetReadyRequest
	6,  // 6: game.network.v2.RoomServiceV2.UpdateRoomState:input_type -> room.UpdateRoomStateRequest
	7,  // 7: game.network.v2.RoomServiceV2.StartMatch:input_type -> room.StartMatchRequest
	8,  // 8: game.network.v2.RoomServiceV2.StreamRoom:input_type -> room.RoomStreamRequest
	9,  // 9: game.network.v2.RoomServiceV2.JoinRoom:output_type -> room.JoinRoomResponse
	10, // 10: game.network.v2.RoomServiceV2.LeaveRoom:output_type -> room.LeaveRoomResponse
	11, // 11: game.network.v2.RoomServiceV2.ListRoom:output_type -> room.ListRoomResponse
	12, // 12: game.network.v2.RoomServiceV2.EnterRing:output_type -> room.EnterRingResponse
	13, // 13: game.network.v2.RoomServiceV2.LeaveRing:output_type -> room.LeaveRingResponse
	14, // 14: game.network.v2.RoomServiceV2.SetReady:output_type -> room.SetReadyResponse
	15, // 15: game.network.v2.RoomServiceV2.UpdateRoomState:output_type -> room.UpdateRoomStateResponse
	16, // 16: game.network.v2.RoomServiceV2.StartMatch:output_type -> room.StartMatchResponse
	11, // 17: game.network.v2.RoomServiceV2.StreamRoom:output_type -> room.ListRoomResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v2_roomV2_proto_init() }
func file_v2_roomV2_proto_init() {
	if File_v2_roomV2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_roomV2_proto_rawDesc), len(file_v2_roomV2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_roomV2_proto_goTypes,
		DependencyIndexes: file_v2_roomV2_proto_depIdxs,
	}.Build()
	File_v2_roomV2_proto = out.File
	file_v2_roomV2_proto_goTypes = nil
	file_v2_roomV2_proto_depIdxs = nil
}
