// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: v2/roomMatchV2.proto

package pbv2

import (
	pb "auxilia/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v2_roomMatchV2_proto protoreflect.FileDescriptor

const file_v2_roomMatchV2_proto_rawDesc = "" +
	"\n" +
	"\x14v2/roomMatchV2.proto\x12\x0fgame.network.v2\x1a\x10room_match.proto2\x90\x02\n" +
	"\x12RoomMatchServiceV2\x12R\n" +
	"\x0fCreateRoomMatch\x12!.roommatch.CreateRoomMatchRequest\x1a\x1c.roommatch.RoomMatchResponse\x12R\n" +
	"\rListRoomMatch\x12\x1f.roommatch.ListRoomMatchRequest\x1a .roommatch.ListRoomMatchResponse\x12R\n" +
	"\x0fUpdateRoomMatch\x12!.roommatch.UpdateRoomMatchRequest\x1a\x1c.roommatch.RoomMatchResponseB&Z\x12auxilia/pb/v2;pbv2\xaa\x02\x0fGame.Network.V2b\x06proto3"

var file_v2_roomMatchV2_proto_goTypes = []any{
	(*pb.CreateRoomMatchRequest)(nil), // 0: roommatch.CreateRoomMatchRequest
	(*pb.ListRoomMatchRequest)(nil),   // 1: roommatch.ListRoomMatchRequest
	(*pb.UpdateRoomMatchRequest)(nil), // 2: roommatch.UpdateRoomMatchRequest
	(*pb.RoomMatchResponse)(nil),      // 3: roommatch.RoomMatchResponse
	(*pb.ListRoomMatchResponse)(nil),  // 4: roommatch.ListRoomMatchResponse
}
var file_v2_roomMatchV2_proto_depIdxs = []int32{
	0, // 0: game.network.v2.RoomMatchServiceV2.CreateRoomMatch:input_type -> roommatch.CreateRoomMatchRequest
	1, // 1: game.network.v2.RoomMatchServiceV2.ListRoomMatch:input_type -> roommatch.ListRoomMatchRequest
	2, // 2: game.network.v2.RoomMatchServiceV2.UpdateRoomMatch:input_type -> roommatch.UpdateRoomMatchRequest
	3, // 3: game.network.v2.RoomMatchServiceV2.CreateRoomMatch:output_type -> roommatch.RoomMatchResponse
	4, // 4: game.network.v2.RoomMatchServiceV2.ListRoomMatch:output_type -> roommatch.ListRoomMatchResponse
	3, // 5: game.network.v2.RoomMatchServiceV2.UpdateRoomMatch:output_type -> roommatch.RoomMatchResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_roomMatchV2_proto_init() }
func file_v2_roomMatchV2_proto_init() {
	if File_v2_roomMatchV2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_roomMatchV2_proto_rawDesc), len(file_v2_roomMatchV2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_roomMatchV2_proto_goTypes,
		DependencyIndexes: file_v2_roomMatchV2_proto_depIdxs,
	}.Build()
	File_v2_roomMatchV2_proto = out.File
	file_v2_roomMatchV2_proto_goTypes = nil
	file_v2_roomMatchV2_proto_depIdxs = nil
}
