// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v2/roomMatchV2.proto

package pbv2

import (
	pb "auxilia/pb"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomMatchServiceV2_CreateRoomMatch_FullMethodName = "/game.network.v2.RoomMatchServiceV2/CreateRoomMatch"
	RoomMatchServiceV2_ListRoomMatch_FullMethodName   = "/game.network.v2.RoomMatchServiceV2/ListRoomMatch"
	RoomMatchServiceV2_UpdateRoomMatch_FullMethodName = "/game.network.v2.RoomMatchServiceV2/UpdateRoomMatch"
)

// RoomMatchServiceV2Client is the client API for RoomMatchServiceV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomMatchServiceV2Client interface {
	CreateRoomMatch(ctx context.Context, in *pb.CreateRoomMatchRequest, opts ...grpc.CallOption) (*pb.RoomMatchResponse, error)
	ListRoomMatch(ctx context.Context, in *pb.ListRoomMatchRequest, opts ...grpc.CallOption) (*pb.ListRoomMatchResponse, error)
	UpdateRoomMatch(ctx context.Context, in *pb.UpdateRoomMatchRequest, opts ...grpc.CallOption) (*pb.RoomMatchResponse, error)
}

type roomMatchServiceV2Client struct {
	cc grpc.ClientConnInterface
}

func NewRoomMatchServiceV2Client(cc grpc.ClientConnInterface) RoomMatchServiceV2Client {
	return &roomMatchServiceV2Client{cc}
}

func (c *roomMatchServiceV2Client) CreateRoomMatch(ctx context.Context, in *pb.CreateRoomMatchRequest, opts ...grpc.CallOption) (*pb.RoomMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.RoomMatchResponse)
	err := c.cc.Invoke(ctx, RoomMatchServiceV2_CreateRoomMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomMatchServiceV2Client) ListRoomMatch(ctx context.Context, in *pb.ListRoomMatchRequest, opts ...grpc.CallOption) (*pb.ListRoomMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.ListRoomMatchResponse)
	err := c.cc.Invoke(ctx, RoomMatchServiceV2_ListRoomMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomMatchServiceV2Client) UpdateRoomMatch(ctx context.Context, in *pb.UpdateRoomMatchRequest, opts ...grpc.CallOption) (*pb.RoomMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.RoomMatchResponse)
	err := c.cc.Invoke(ctx, RoomMatchServiceV2_UpdateRoomMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomMatchServiceV2Server is the server API for RoomMatchServiceV2 service.
// All implementations must embed UnimplementedRoomMatchServiceV2Server
// for forward compatibility.
type RoomMatchServiceV2Server interface {
	CreateRoomMatch(context.Context, *pb.CreateRoomMatchRequest) (*pb.RoomMatchResponse, error)
	ListRoomMatch(context.Context, *pb.ListRoomMatchRequest) (*pb.ListRoomMatchResponse, error)
	UpdateRoomMatch(context.Context, *pb.UpdateRoomMatchRequest) (*pb.RoomMatchResponse, error)
	mustEmbedUnimplementedRoomMatchServiceV2Server()
}

// UnimplementedRoomMatchServiceV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomMatchServiceV2Server struct{}

func (UnimplementedRoomMatchServiceV2Server) CreateRoomMatch(context.Context, *pb.CreateRoomMatchRequest) (*pb.RoomMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoomMatch not implemented")
}
func (UnimplementedRoomMatchServiceV2Server) ListRoomMatch(context.Context, *pb.ListRoomMatchRequest) (*pb.ListRoomMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoomMatch not implemented")
}
func (UnimplementedRoomMatchServiceV2Server) UpdateRoomMatch(context.Context, *pb.UpdateRoomMatchRequest) (*pb.RoomMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoomMatch not implemented")
}
func (UnimplementedRoomMatchServiceV2Server) mustEmbedUnimplementedRoomMatchServiceV2Server() {}
func (UnimplementedRoomMatchServiceV2Server) testEmbeddedByValue()                            {}

// UnsafeRoomMatchServiceV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomMatchServiceV2Server will
// result in compilation errors.
type UnsafeRoomMatchServiceV2Server interface {
	mustEmbedUnimplementedRoomMatchServiceV2Server()
}

func RegisterRoomMatchServiceV2Server(s grpc.ServiceRegistrar, srv RoomMatchServiceV2Server) {
	// If the following call pancis, it indicates UnimplementedRoomMatchServiceV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomMatchServiceV2_ServiceDesc, srv)
}

func _RoomMatchServiceV2_CreateRoomMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.CreateRoomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomMatchServiceV2Server).CreateRoomMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomMatchServiceV2_CreateRoomMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomMatchServiceV2Server).CreateRoomMatch(ctx, req.(*pb.CreateRoomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomMatchServiceV2_ListRoomMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.ListRoomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomMatchServiceV2Server).ListRoomMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomMatchServiceV2_ListRoomMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomMatchServiceV2Server).ListRoomMatch(ctx, req.(*pb.ListRoomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomMatchServiceV2_UpdateRoomMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.UpdateRoomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomMatchServiceV2Server).UpdateRoomMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomMatchServiceV2_UpdateRoomMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomMatchServiceV2Server).UpdateRoomMatch(ctx, req.(*pb.UpdateRoomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomMatchServiceV2_ServiceDesc is the grpc.ServiceDesc for RoomMatchServiceV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomMatchServiceV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.network.v2.RoomMatchServiceV2",
	HandlerType: (*RoomMatchServiceV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoomMatch",
			Handler:    _RoomMatchServiceV2_CreateRoomMatch_Handler,
		},
		{
			MethodName: "ListRoomMatch",
			Handler:    _RoomMatchServiceV2_ListRoomMatch_Handler,
		},
		{
			MethodName: "UpdateRoomMatch",
			Handler:    _RoomMatchServiceV2_UpdateRoomMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/roomMatchV2.proto",
}
