// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Player_1PId   string                 `protobuf:"bytes,2,opt,name=player_1p_id,json=player1pId,proto3" json:"player_1p_id,omitempty"`
	Player_2PId   string                 `protobuf:"bytes,3,opt,name=player_2p_id,json=player2pId,proto3" json:"player_2p_id,omitempty"`
	BaseHp_1P     int32                  `protobuf:"varint,4,opt,name=base_hp_1p,json=baseHp1p,proto3" json:"base_hp_1p,omitempty"`
	BaseHp_2P     int32                  `protobuf:"varint,5,opt,name=base_hp_2p,json=baseHp2p,proto3" json:"base_hp_2p,omitempty"`
	Turn          uint32                 `protobuf:"varint,6,opt,name=turn,proto3" json:"turn,omitempty"`
	Characters    []*UniqueCharacter     `protobuf:"bytes,7,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Game) GetPlayer_1PId() string {
	if x != nil {
		return x.Player_1PId
	}
	return ""
}

func (x *Game) GetPlayer_2PId() string {
	if x != nil {
		return x.Player_2PId
	}
	return ""
}

func (x *Game) GetBaseHp_1P() int32 {
	if x != nil {
		return x.BaseHp_1P
	}
	return 0
}

func (x *Game) GetBaseHp_2P() int32 {
	if x != nil {
		return x.BaseHp_2P
	}
	return 0
}

func (x *Game) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *Game) GetCharacters() []*UniqueCharacter {
	if x != nil {
		return x.Characters
	}
	return nil
}

type SaveGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameRequest) Reset() {
	*x = SaveGameRequest{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameRequest) ProtoMessage() {}

func (x *SaveGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameRequest.ProtoReflect.Descriptor instead.
func (*SaveGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *SaveGameRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type UpdateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameRequest) Reset() {
	*x = UpdateGameRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameRequest) ProtoMessage() {}

func (x *UpdateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateGameRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type DeleteGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameRequest) Reset() {
	*x = DeleteGameRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameRequest) ProtoMessage() {}

func (x *DeleteGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteGameRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type ListGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

type GameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Game          *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type DeleteGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameResponse) Reset() {
	*x = DeleteGameResponse{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameResponse) ProtoMessage() {}

func (x *DeleteGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *ListGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type UniqueCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Hp            int32                  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Is_1P         bool                   `protobuf:"varint,5,opt,name=is_1p,json=is1p,proto3" json:"is_1p,omitempty"`
	Conditions    []*CharacterCondition  `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueCharacter) Reset() {
	*x = UniqueCharacter{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueCharacter) ProtoMessage() {}

func (x *UniqueCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueCharacter.ProtoReflect.Descriptor instead.
func (*UniqueCharacter) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *UniqueCharacter) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UniqueCharacter) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *UniqueCharacter) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *UniqueCharacter) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *UniqueCharacter) GetIs_1P() bool {
	if x != nil {
		return x.Is_1P
	}
	return false
}

func (x *UniqueCharacter) GetConditions() []*CharacterCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type CharacterCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConditionId   uint32                 `protobuf:"varint,1,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	LastingTurn   uint32                 `protobuf:"varint,2,opt,name=lasting_turn,json=lastingTurn,proto3" json:"lasting_turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterCondition) Reset() {
	*x = CharacterCondition{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCondition) ProtoMessage() {}

func (x *CharacterCondition) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCondition.ProtoReflect.Descriptor instead.
func (*CharacterCondition) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *CharacterCondition) GetConditionId() uint32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

func (x *CharacterCondition) GetLastingTurn() uint32 {
	if x != nil {
		return x.LastingTurn
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"\xea\x01\n" +
	"\x04Game\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12 \n" +
	"\fplayer_1p_id\x18\x02 \x01(\tR\n" +
	"player1pId\x12 \n" +
	"\fplayer_2p_id\x18\x03 \x01(\tR\n" +
	"player2pId\x12\x1c\n" +
	"\n" +
	"base_hp_1p\x18\x04 \x01(\x05R\bbaseHp1p\x12\x1c\n" +
	"\n" +
	"base_hp_2p\x18\x05 \x01(\x05R\bbaseHp2p\x12\x12\n" +
	"\x04turn\x18\x06 \x01(\rR\x04turn\x125\n" +
	"\n" +
	"characters\x18\a \x03(\v2\x15.game.UniqueCharacterR\n" +
	"characters\"1\n" +
	"\x0fSaveGameRequest\x12\x1e\n" +
	"\x04game\x18\x01 \x01(\v2\n" +
	".game.GameR\x04game\"3\n" +
	"\x11UpdateGameRequest\x12\x1e\n" +
	"\x04game\x18\x01 \x01(\v2\n" +
	".game.GameR\x04game\")\n" +
	"\x0eGetGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\",\n" +
	"\x11DeleteGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\"\x12\n" +
	"\x10ListGamesRequest\"H\n" +
	"\fGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1e\n" +
	"\x04game\x18\x02 \x01(\v2\n" +
	".game.GameR\x04game\".\n" +
	"\x12DeleteGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x11ListGamesResponse\x12 \n" +
	"\x05games\x18\x01 \x03(\v2\n" +
	".game.GameR\x05games\"\xaf\x01\n" +
	"\x0fUniqueCharacter\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\x05R\x02hp\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x13\n" +
	"\x05is_1p\x18\x05 \x01(\bR\x04is1p\x128\n" +
	"\n" +
	"conditions\x18\x06 \x03(\v2\x18.game.CharacterConditionR\n" +
	"conditions\"Z\n" +
	"\x12CharacterCondition\x12!\n" +
	"\fcondition_id\x18\x01 \x01(\rR\vconditionId\x12!\n" +
	"\flasting_turn\x18\x02 \x01(\rR\vlastingTurn2\xb3\x02\n" +
	"\vGameService\x125\n" +
	"\bSaveGame\x12\x15.game.SaveGameRequest\x1a\x12.game.GameResponse\x123\n" +
	"\aGetGame\x12\x14.game.GetGameRequest\x1a\x12.game.GameResponse\x129\n" +
	"\n" +
	"UpdateGame\x12\x17.game.UpdateGameRequest\x1a\x12.game.GameResponse\x12?\n" +
	"\n" +
	"DeleteGame\x12\x17.game.DeleteGameRequest\x1a\x18.game.DeleteGameResponse\x12<\n" +
	"\tListGames\x12\x16.game.ListGamesRequest\x1a\x17.game.ListGamesResponseB\x1bZ\n" +
	"auxilia/pb\xaa\x02\fGame.Networkb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_game_proto_goTypes = []any{
	(*Game)(nil),               // 0: game.Game
	(*SaveGameRequest)(nil),    // 1: game.SaveGameRequest
	(*UpdateGameRequest)(nil),  // 2: game.UpdateGameRequest
	(*GetGameRequest)(nil),     // 3: game.GetGameRequest
	(*DeleteGameRequest)(nil),  // 4: game.DeleteGameRequest
	(*ListGamesRequest)(nil),   // 5: game.ListGamesRequest
	(*GameResponse)(nil),       // 6: game.GameResponse
	(*DeleteGameResponse)(nil), // 7: game.DeleteGameResponse
	(*ListGamesResponse)(nil),  // 8: game.ListGamesResponse
	(*UniqueCharacter)(nil),    // 9: game.UniqueCharacter
	(*CharacterCondition)(nil), // 10: game.CharacterCondition
}
var file_game_proto_depIdxs = []int32{
	9,  // 0: game.Game.characters:type_name -> game.UniqueCharacter
	0,  // 1: game.SaveGameRequest.game:type_name -> game.Game
	0,  // 2: game.UpdateGameRequest.game:type_name -> game.Game
	0,  // 3: game.GameResponse.game:type_name -> game.Game
	0,  // 4: game.ListGamesResponse.games:type_name -> game.Game
	10, // 5: game.UniqueCharacter.conditions:type_name -> game.CharacterCondition
	1,  // 6: game.GameService.SaveGame:input_type -> game.SaveGameRequest
	3,  // 7: game.GameService.GetGame:input_type -> game.GetGameRequest
	2,  // 8: game.GameService.UpdateGame:input_type -> game.UpdateGameRequest
	4,  // 9: game.GameService.DeleteGame:input_type -> game.DeleteGameRequest
	5,  // 10: game.GameService.ListGames:input_type -> game.ListGamesRequest
	6,  // 11: game.GameService.SaveGame:output_type -> game.GameResponse
	6,  // 12: game.GameService.GetGame:output_type -> game.GameResponse
	6,  // 13: game.GameService.UpdateGame:output_type -> game.GameResponse
	7,  // 14: game.GameService.DeleteGame:output_type -> game.DeleteGameResponse
	8,  // 15: game.GameService.ListGames:output_type -> game.ListGamesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
