// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 状態異常の情報
type CharacterCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConditionId   uint32                 `protobuf:"varint,1,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	LastingTurn   uint32                 `protobuf:"varint,2,opt,name=lasting_turn,json=lastingTurn,proto3" json:"lasting_turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterCondition) Reset() {
	*x = CharacterCondition{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCondition) ProtoMessage() {}

func (x *CharacterCondition) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCondition.ProtoReflect.Descriptor instead.
func (*CharacterCondition) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterCondition) GetConditionId() uint32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

func (x *CharacterCondition) GetLastingTurn() uint32 {
	if x != nil {
		return x.LastingTurn
	}
	return 0
}

// キャラクター個別の情報
type UniqueCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Hp            int32                  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Is_1P         bool                   `protobuf:"varint,5,opt,name=is_1p,json=is1p,proto3" json:"is_1p,omitempty"`
	Conditions    []*CharacterCondition  `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueCharacter) Reset() {
	*x = UniqueCharacter{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueCharacter) ProtoMessage() {}

func (x *UniqueCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueCharacter.ProtoReflect.Descriptor instead.
func (*UniqueCharacter) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *UniqueCharacter) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UniqueCharacter) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *UniqueCharacter) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *UniqueCharacter) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *UniqueCharacter) GetIs_1P() bool {
	if x != nil {
		return x.Is_1P
	}
	return false
}

func (x *UniqueCharacter) GetConditions() []*CharacterCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// 試合保存のリクエスト
type SaveGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Player_1PId   string                 `protobuf:"bytes,2,opt,name=player_1p_id,json=player1pId,proto3" json:"player_1p_id,omitempty"`
	Player_2PId   string                 `protobuf:"bytes,3,opt,name=player_2p_id,json=player2pId,proto3" json:"player_2p_id,omitempty"`
	BaseHp_1P     int32                  `protobuf:"varint,4,opt,name=base_hp_1p,json=baseHp1p,proto3" json:"base_hp_1p,omitempty"`
	BaseHp_2P     int32                  `protobuf:"varint,5,opt,name=base_hp_2p,json=baseHp2p,proto3" json:"base_hp_2p,omitempty"`
	Turn          uint32                 `protobuf:"varint,6,opt,name=turn,proto3" json:"turn,omitempty"`
	Characters    []*UniqueCharacter     `protobuf:"bytes,7,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameRequest) Reset() {
	*x = SaveGameRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameRequest) ProtoMessage() {}

func (x *SaveGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameRequest.ProtoReflect.Descriptor instead.
func (*SaveGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *SaveGameRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SaveGameRequest) GetPlayer_1PId() string {
	if x != nil {
		return x.Player_1PId
	}
	return ""
}

func (x *SaveGameRequest) GetPlayer_2PId() string {
	if x != nil {
		return x.Player_2PId
	}
	return ""
}

func (x *SaveGameRequest) GetBaseHp_1P() int32 {
	if x != nil {
		return x.BaseHp_1P
	}
	return 0
}

func (x *SaveGameRequest) GetBaseHp_2P() int32 {
	if x != nil {
		return x.BaseHp_2P
	}
	return 0
}

func (x *SaveGameRequest) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *SaveGameRequest) GetCharacters() []*UniqueCharacter {
	if x != nil {
		return x.Characters
	}
	return nil
}

type SaveGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameResponse) Reset() {
	*x = SaveGameResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameResponse) ProtoMessage() {}

func (x *SaveGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameResponse.ProtoReflect.Descriptor instead.
func (*SaveGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *SaveGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 試合削除のリクエスト
type DeleteGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameRequest) Reset() {
	*x = DeleteGameRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameRequest) ProtoMessage() {}

func (x *DeleteGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteGameRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type DeleteGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameResponse) Reset() {
	*x = DeleteGameResponse{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameResponse) ProtoMessage() {}

func (x *DeleteGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*SaveGameRequest     `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *ListGamesResponse) GetGames() []*SaveGameRequest {
	if x != nil {
		return x.Games
	}
	return nil
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x02pb\"Z\n" +
	"\x12CharacterCondition\x12!\n" +
	"\fcondition_id\x18\x01 \x01(\rR\vconditionId\x12!\n" +
	"\flasting_turn\x18\x02 \x01(\rR\vlastingTurn\"\xad\x01\n" +
	"\x0fUniqueCharacter\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\x05R\x02hp\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x13\n" +
	"\x05is_1p\x18\x05 \x01(\bR\x04is1p\x126\n" +
	"\n" +
	"conditions\x18\x06 \x03(\v2\x16.pb.CharacterConditionR\n" +
	"conditions\"\xf3\x01\n" +
	"\x0fSaveGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12 \n" +
	"\fplayer_1p_id\x18\x02 \x01(\tR\n" +
	"player1pId\x12 \n" +
	"\fplayer_2p_id\x18\x03 \x01(\tR\n" +
	"player2pId\x12\x1c\n" +
	"\n" +
	"base_hp_1p\x18\x04 \x01(\x05R\bbaseHp1p\x12\x1c\n" +
	"\n" +
	"base_hp_2p\x18\x05 \x01(\x05R\bbaseHp2p\x12\x12\n" +
	"\x04turn\x18\x06 \x01(\rR\x04turn\x123\n" +
	"\n" +
	"characters\x18\a \x03(\v2\x13.pb.UniqueCharacterR\n" +
	"characters\",\n" +
	"\x10SaveGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11DeleteGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\".\n" +
	"\x12DeleteGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10ListGamesRequest\">\n" +
	"\x11ListGamesResponse\x12)\n" +
	"\x05games\x18\x01 \x03(\v2\x13.pb.SaveGameRequestR\x05games2\xbb\x01\n" +
	"\vGameService\x125\n" +
	"\bSaveGame\x12\x13.pb.SaveGameRequest\x1a\x14.pb.SaveGameResponse\x12;\n" +
	"\n" +
	"DeleteGame\x12\x15.pb.DeleteGameRequest\x1a\x16.pb.DeleteGameResponse\x128\n" +
	"\tListGames\x12\x14.pb.ListGamesRequest\x1a\x15.pb.ListGamesResponseB\fZ\n" +
	"auxilia/pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_proto_goTypes = []any{
	(*CharacterCondition)(nil), // 0: pb.CharacterCondition
	(*UniqueCharacter)(nil),    // 1: pb.UniqueCharacter
	(*SaveGameRequest)(nil),    // 2: pb.SaveGameRequest
	(*SaveGameResponse)(nil),   // 3: pb.SaveGameResponse
	(*DeleteGameRequest)(nil),  // 4: pb.DeleteGameRequest
	(*DeleteGameResponse)(nil), // 5: pb.DeleteGameResponse
	(*ListGamesRequest)(nil),   // 6: pb.ListGamesRequest
	(*ListGamesResponse)(nil),  // 7: pb.ListGamesResponse
}
var file_game_proto_depIdxs = []int32{
	0, // 0: pb.UniqueCharacter.conditions:type_name -> pb.CharacterCondition
	1, // 1: pb.SaveGameRequest.characters:type_name -> pb.UniqueCharacter
	2, // 2: pb.ListGamesResponse.games:type_name -> pb.SaveGameRequest
	2, // 3: pb.GameService.SaveGame:input_type -> pb.SaveGameRequest
	4, // 4: pb.GameService.DeleteGame:input_type -> pb.DeleteGameRequest
	6, // 5: pb.GameService.ListGames:input_type -> pb.ListGamesRequest
	3, // 6: pb.GameService.SaveGame:output_type -> pb.SaveGameResponse
	5, // 7: pb.GameService.DeleteGame:output_type -> pb.DeleteGameResponse
	7, // 8: pb.GameService.ListGames:output_type -> pb.ListGamesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
