// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/game.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleService_CreateGame_FullMethodName         = "/game.network.BattleService/CreateGame"
	BattleService_GetGameData_FullMethodName        = "/game.network.BattleService/GetGameData"
	BattleService_RegisterCharacters_FullMethodName = "/game.network.BattleService/RegisterCharacters"
	BattleService_StreamGame_FullMethodName         = "/game.network.BattleService/StreamGame"
	BattleService_ApplyMove_FullMethodName          = "/game.network.BattleService/ApplyMove"
	BattleService_ApplyAttack_FullMethodName        = "/game.network.BattleService/ApplyAttack"
	BattleService_EndTurn_FullMethodName            = "/game.network.BattleService/EndTurn"
	BattleService_ApplyGridUpdate_FullMethodName    = "/game.network.BattleService/ApplyGridUpdate"
)

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BattleServiceClient interface {
	// 試合の初期登録
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*GameDataResponse, error)
	// 現在の試合情報の取得
	GetGameData(ctx context.Context, in *GetGameDataRequest, opts ...grpc.CallOption) (*GameDataResponse, error)
	RegisterCharacters(ctx context.Context, in *RegisterCharactersRequest, opts ...grpc.CallOption) (*RegisterCharactersResponse, error)
	// 対戦中のアクション同期（サーバー・ストリーミング）
	// ルームIDを指定して受信を開始する
	StreamGame(ctx context.Context, in *StreamGameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameDataResponse], error)
	// アクション送信（個別の単方向RPC）
	ApplyMove(ctx context.Context, in *PlayerAction, opts ...grpc.CallOption) (*GameDataResponse, error)
	ApplyAttack(ctx context.Context, in *PlayerAction, opts ...grpc.CallOption) (*GameDataResponse, error)
	EndTurn(ctx context.Context, in *PlayerAction, opts ...grpc.CallOption) (*GameDataResponse, error)
	ApplyGridUpdate(ctx context.Context, in *PlayerAction, opts ...grpc.CallOption) (*GameDataResponse, error)
}

type battleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleServiceClient(cc grpc.ClientConnInterface) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*GameDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDataResponse)
	err := c.cc.Invoke(ctx, BattleService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) GetGameData(ctx context.Context, in *GetGameDataRequest, opts ...grpc.CallOption) (*GameDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDataResponse)
	err := c.cc.Invoke(ctx, BattleService_GetGameData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) RegisterCharacters(ctx context.Context, in *RegisterCharactersRequest, opts ...grpc.CallOption) (*RegisterCharactersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterCharactersResponse)
	err := c.cc.Invoke(ctx, BattleService_RegisterCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) StreamGame(ctx context.Context, in *StreamGameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BattleService_ServiceDesc.Streams[0], BattleService_StreamGame_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamGameRequest, GameDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleService_StreamGameClient = grpc.ServerStreamingClient[GameDataResponse]

func (c *battleServiceClient) ApplyMove(ctx context.Context, in *PlayerAction, opts ...grpc.CallOption) (*GameDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDataResponse)
	err := c.cc.Invoke(ctx, BattleService_ApplyMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) ApplyAttack(ctx context.Context, in *PlayerAction, opts ...grpc.CallOption) (*GameDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDataResponse)
	err := c.cc.Invoke(ctx, BattleService_ApplyAttack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) EndTurn(ctx context.Context, in *PlayerAction, opts ...grpc.CallOption) (*GameDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDataResponse)
	err := c.cc.Invoke(ctx, BattleService_EndTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *battleServiceClient) ApplyGridUpdate(ctx context.Context, in *PlayerAction, opts ...grpc.CallOption) (*GameDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameDataResponse)
	err := c.cc.Invoke(ctx, BattleService_ApplyGridUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleServiceServer is the server API for BattleService service.
// All implementations must embed UnimplementedBattleServiceServer
// for forward compatibility.
type BattleServiceServer interface {
	// 試合の初期登録
	CreateGame(context.Context, *CreateGameRequest) (*GameDataResponse, error)
	// 現在の試合情報の取得
	GetGameData(context.Context, *GetGameDataRequest) (*GameDataResponse, error)
	RegisterCharacters(context.Context, *RegisterCharactersRequest) (*RegisterCharactersResponse, error)
	// 対戦中のアクション同期（サーバー・ストリーミング）
	// ルームIDを指定して受信を開始する
	StreamGame(*StreamGameRequest, grpc.ServerStreamingServer[GameDataResponse]) error
	// アクション送信（個別の単方向RPC）
	ApplyMove(context.Context, *PlayerAction) (*GameDataResponse, error)
	ApplyAttack(context.Context, *PlayerAction) (*GameDataResponse, error)
	EndTurn(context.Context, *PlayerAction) (*GameDataResponse, error)
	ApplyGridUpdate(context.Context, *PlayerAction) (*GameDataResponse, error)
	mustEmbedUnimplementedBattleServiceServer()
}

// UnimplementedBattleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleServiceServer struct{}

func (UnimplementedBattleServiceServer) CreateGame(context.Context, *CreateGameRequest) (*GameDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedBattleServiceServer) GetGameData(context.Context, *GetGameDataRequest) (*GameDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameData not implemented")
}
func (UnimplementedBattleServiceServer) RegisterCharacters(context.Context, *RegisterCharactersRequest) (*RegisterCharactersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCharacters not implemented")
}
func (UnimplementedBattleServiceServer) StreamGame(*StreamGameRequest, grpc.ServerStreamingServer[GameDataResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamGame not implemented")
}
func (UnimplementedBattleServiceServer) ApplyMove(context.Context, *PlayerAction) (*GameDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyMove not implemented")
}
func (UnimplementedBattleServiceServer) ApplyAttack(context.Context, *PlayerAction) (*GameDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyAttack not implemented")
}
func (UnimplementedBattleServiceServer) EndTurn(context.Context, *PlayerAction) (*GameDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndTurn not implemented")
}
func (UnimplementedBattleServiceServer) ApplyGridUpdate(context.Context, *PlayerAction) (*GameDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyGridUpdate not implemented")
}
func (UnimplementedBattleServiceServer) mustEmbedUnimplementedBattleServiceServer() {}
func (UnimplementedBattleServiceServer) testEmbeddedByValue()                       {}

// UnsafeBattleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleServiceServer will
// result in compilation errors.
type UnsafeBattleServiceServer interface {
	mustEmbedUnimplementedBattleServiceServer()
}

func RegisterBattleServiceServer(s grpc.ServiceRegistrar, srv BattleServiceServer) {
	// If the following call panics, it indicates UnimplementedBattleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleService_ServiceDesc, srv)
}

func _BattleService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_GetGameData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).GetGameData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_GetGameData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).GetGameData(ctx, req.(*GetGameDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_RegisterCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCharactersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).RegisterCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_RegisterCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).RegisterCharacters(ctx, req.(*RegisterCharactersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_StreamGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamGameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BattleServiceServer).StreamGame(m, &grpc.GenericServerStream[StreamGameRequest, GameDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BattleService_StreamGameServer = grpc.ServerStreamingServer[GameDataResponse]

func _BattleService_ApplyMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).ApplyMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_ApplyMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).ApplyMove(ctx, req.(*PlayerAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_ApplyAttack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).ApplyAttack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_ApplyAttack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).ApplyAttack(ctx, req.(*PlayerAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_EndTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).EndTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_EndTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).EndTurn(ctx, req.(*PlayerAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _BattleService_ApplyGridUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).ApplyGridUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleService_ApplyGridUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).ApplyGridUpdate(ctx, req.(*PlayerAction))
	}
	return interceptor(ctx, in, info, handler)
}

// BattleService_ServiceDesc is the grpc.ServiceDesc for BattleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.network.BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _BattleService_CreateGame_Handler,
		},
		{
			MethodName: "GetGameData",
			Handler:    _BattleService_GetGameData_Handler,
		},
		{
			MethodName: "RegisterCharacters",
			Handler:    _BattleService_RegisterCharacters_Handler,
		},
		{
			MethodName: "ApplyMove",
			Handler:    _BattleService_ApplyMove_Handler,
		},
		{
			MethodName: "ApplyAttack",
			Handler:    _BattleService_ApplyAttack_Handler,
		},
		{
			MethodName: "EndTurn",
			Handler:    _BattleService_EndTurn_Handler,
		},
		{
			MethodName: "ApplyGridUpdate",
			Handler:    _BattleService_ApplyGridUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGame",
			Handler:       _BattleService_StreamGame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/game.proto",
}
