// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 試合登録用リクエスト
type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Player1Id     string                 `protobuf:"bytes,2,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player2Id     string                 `protobuf:"bytes,3,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateGameRequest) GetPlayer1Id() string {
	if x != nil {
		return x.Player1Id
	}
	return ""
}

func (x *CreateGameRequest) GetPlayer2Id() string {
	if x != nil {
		return x.Player2Id
	}
	return ""
}

type StreamGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamGameRequest) Reset() {
	*x = StreamGameRequest{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGameRequest) ProtoMessage() {}

func (x *StreamGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGameRequest.ProtoReflect.Descriptor instead.
func (*StreamGameRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *StreamGameRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StreamGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GridUpdateAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Grids         []*GridInfo            `protobuf:"bytes,3,rep,name=grids,proto3" json:"grids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridUpdateAction) Reset() {
	*x = GridUpdateAction{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridUpdateAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridUpdateAction) ProtoMessage() {}

func (x *GridUpdateAction) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridUpdateAction.ProtoReflect.Descriptor instead.
func (*GridUpdateAction) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *GridUpdateAction) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GridUpdateAction) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GridUpdateAction) GetGrids() []*GridInfo {
	if x != nil {
		return x.Grids
	}
	return nil
}

type MoveAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CharacterId   uint32                 `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ToX           uint32                 `protobuf:"varint,4,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY           uint32                 `protobuf:"varint,5,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveAction) Reset() {
	*x = MoveAction{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveAction) ProtoMessage() {}

func (x *MoveAction) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveAction.ProtoReflect.Descriptor instead.
func (*MoveAction) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *MoveAction) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MoveAction) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MoveAction) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *MoveAction) GetToX() uint32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *MoveAction) GetToY() uint32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

type AttackAction struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoomId              uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId            string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AttackerCharacterId uint32                 `protobuf:"varint,3,opt,name=attacker_character_id,json=attackerCharacterId,proto3" json:"attacker_character_id,omitempty"`
	AttackType          int32                  `protobuf:"varint,4,opt,name=attack_type,json=attackType,proto3" json:"attack_type,omitempty"`
	AttackInfos         []*AttackInfo          `protobuf:"bytes,8,rep,name=attack_infos,json=attackInfos,proto3" json:"attack_infos,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttackAction) Reset() {
	*x = AttackAction{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackAction) ProtoMessage() {}

func (x *AttackAction) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackAction.ProtoReflect.Descriptor instead.
func (*AttackAction) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *AttackAction) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AttackAction) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *AttackAction) GetAttackerCharacterId() uint32 {
	if x != nil {
		return x.AttackerCharacterId
	}
	return 0
}

func (x *AttackAction) GetAttackType() int32 {
	if x != nil {
		return x.AttackType
	}
	return 0
}

func (x *AttackAction) GetAttackInfos() []*AttackInfo {
	if x != nil {
		return x.AttackInfos
	}
	return nil
}

type AttackInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AttackedCharacterId uint32                 `protobuf:"varint,1,opt,name=attacked_character_id,json=attackedCharacterId,proto3" json:"attacked_character_id,omitempty"` //base1=98,base2=99
	NewHp               uint32                 `protobuf:"varint,2,opt,name=new_hp,json=newHp,proto3" json:"new_hp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttackInfo) Reset() {
	*x = AttackInfo{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackInfo) ProtoMessage() {}

func (x *AttackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackInfo.ProtoReflect.Descriptor instead.
func (*AttackInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *AttackInfo) GetAttackedCharacterId() uint32 {
	if x != nil {
		return x.AttackedCharacterId
	}
	return 0
}

func (x *AttackInfo) GetNewHp() uint32 {
	if x != nil {
		return x.NewHp
	}
	return 0
}

// 試合情報全体のレスポンス
type GameDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId         uint32                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Player1Id      string                 `protobuf:"bytes,3,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player2Id      string                 `protobuf:"bytes,4,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
	BaseHp1        uint32                 `protobuf:"varint,5,opt,name=base_hp1,json=baseHp1,proto3" json:"base_hp1,omitempty"`
	BaseHp2        uint32                 `protobuf:"varint,6,opt,name=base_hp2,json=baseHp2,proto3" json:"base_hp2,omitempty"`
	Turn           uint32                 `protobuf:"varint,7,opt,name=turn,proto3" json:"turn,omitempty"`
	Is_1PTurn      bool                   `protobuf:"varint,8,opt,name=is_1p_turn,json=is1pTurn,proto3" json:"is_1p_turn,omitempty"`
	TurnStartAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=turn_start_at,json=turnStartAt,proto3" json:"turn_start_at,omitempty"`
	Characters     []*UniqueCharacter     `protobuf:"bytes,10,rep,name=characters,proto3" json:"characters,omitempty"`
	IsFinished     bool                   `protobuf:"varint,11,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	WinnerPlayerId string                 `protobuf:"bytes,12,opt,name=winner_player_id,json=winnerPlayerId,proto3" json:"winner_player_id,omitempty"`
	FinishedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	AttackInfos    []*AttackInfo          `protobuf:"bytes,14,rep,name=attack_infos,json=attackInfos,proto3" json:"attack_infos,omitempty"`
	Grids          []*GridInfo            `protobuf:"bytes,15,rep,name=grids,proto3" json:"grids,omitempty"`
	Cost_1P        uint32                 `protobuf:"varint,16,opt,name=cost_1p,json=cost1p,proto3" json:"cost_1p,omitempty"`
	Cost_2P        uint32                 `protobuf:"varint,17,opt,name=cost_2p,json=cost2p,proto3" json:"cost_2p,omitempty"`
	P1RateDelta    int32                  `protobuf:"varint,18,opt,name=p1_rate_delta,json=p1RateDelta,proto3" json:"p1_rate_delta,omitempty"`
	P2RateDelta    int32                  `protobuf:"varint,19,opt,name=p2_rate_delta,json=p2RateDelta,proto3" json:"p2_rate_delta,omitempty"`
	P1Rate         int32                  `protobuf:"varint,20,opt,name=p1_rate,json=p1Rate,proto3" json:"p1_rate,omitempty"`
	P2Rate         int32                  `protobuf:"varint,21,opt,name=p2_rate,json=p2Rate,proto3" json:"p2_rate,omitempty"`
	GameActionLog  *GameActionLog         `protobuf:"bytes,22,opt,name=game_action_log,json=gameActionLog,proto3" json:"game_action_log,omitempty"`
	IsTurnEnded    bool                   `protobuf:"varint,23,opt,name=is_turn_ended,json=isTurnEnded,proto3" json:"is_turn_ended,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameDataResponse) Reset() {
	*x = GameDataResponse{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDataResponse) ProtoMessage() {}

func (x *GameDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDataResponse.ProtoReflect.Descriptor instead.
func (*GameDataResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameDataResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameDataResponse) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GameDataResponse) GetPlayer1Id() string {
	if x != nil {
		return x.Player1Id
	}
	return ""
}

func (x *GameDataResponse) GetPlayer2Id() string {
	if x != nil {
		return x.Player2Id
	}
	return ""
}

func (x *GameDataResponse) GetBaseHp1() uint32 {
	if x != nil {
		return x.BaseHp1
	}
	return 0
}

func (x *GameDataResponse) GetBaseHp2() uint32 {
	if x != nil {
		return x.BaseHp2
	}
	return 0
}

func (x *GameDataResponse) GetTurn() uint32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *GameDataResponse) GetIs_1PTurn() bool {
	if x != nil {
		return x.Is_1PTurn
	}
	return false
}

func (x *GameDataResponse) GetTurnStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TurnStartAt
	}
	return nil
}

func (x *GameDataResponse) GetCharacters() []*UniqueCharacter {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *GameDataResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *GameDataResponse) GetWinnerPlayerId() string {
	if x != nil {
		return x.WinnerPlayerId
	}
	return ""
}

func (x *GameDataResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *GameDataResponse) GetAttackInfos() []*AttackInfo {
	if x != nil {
		return x.AttackInfos
	}
	return nil
}

func (x *GameDataResponse) GetGrids() []*GridInfo {
	if x != nil {
		return x.Grids
	}
	return nil
}

func (x *GameDataResponse) GetCost_1P() uint32 {
	if x != nil {
		return x.Cost_1P
	}
	return 0
}

func (x *GameDataResponse) GetCost_2P() uint32 {
	if x != nil {
		return x.Cost_2P
	}
	return 0
}

func (x *GameDataResponse) GetP1RateDelta() int32 {
	if x != nil {
		return x.P1RateDelta
	}
	return 0
}

func (x *GameDataResponse) GetP2RateDelta() int32 {
	if x != nil {
		return x.P2RateDelta
	}
	return 0
}

func (x *GameDataResponse) GetP1Rate() int32 {
	if x != nil {
		return x.P1Rate
	}
	return 0
}

func (x *GameDataResponse) GetP2Rate() int32 {
	if x != nil {
		return x.P2Rate
	}
	return 0
}

func (x *GameDataResponse) GetGameActionLog() *GameActionLog {
	if x != nil {
		return x.GameActionLog
	}
	return nil
}

func (x *GameDataResponse) GetIsTurnEnded() bool {
	if x != nil {
		return x.IsTurnEnded
	}
	return false
}

type GridInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionX     uint32                 `protobuf:"varint,1,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY     uint32                 `protobuf:"varint,2,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	GridType      int32                  `protobuf:"varint,3,opt,name=grid_type,json=gridType,proto3" json:"grid_type,omitempty"`
	IsSelected    bool                   `protobuf:"varint,4,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
	IsAttackRange bool                   `protobuf:"varint,5,opt,name=is_attack_range,json=isAttackRange,proto3" json:"is_attack_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridInfo) Reset() {
	*x = GridInfo{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridInfo) ProtoMessage() {}

func (x *GridInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridInfo.ProtoReflect.Descriptor instead.
func (*GridInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *GridInfo) GetPositionX() uint32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *GridInfo) GetPositionY() uint32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *GridInfo) GetGridType() int32 {
	if x != nil {
		return x.GridType
	}
	return 0
}

func (x *GridInfo) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

func (x *GridInfo) GetIsAttackRange() bool {
	if x != nil {
		return x.IsAttackRange
	}
	return false
}

type UniqueCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CharacterId   uint32                 `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Is_1P         bool                   `protobuf:"varint,3,opt,name=is_1p,json=is1p,proto3" json:"is_1p,omitempty"`
	Hp            uint32                 `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	PositionX     uint32                 `protobuf:"varint,5,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY     uint32                 `protobuf:"varint,6,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	Conditions    []*CharacterCondition  `protobuf:"bytes,7,rep,name=conditions,proto3" json:"conditions,omitempty"`
	IsSelected    bool                   `protobuf:"varint,8,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueCharacter) Reset() {
	*x = UniqueCharacter{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueCharacter) ProtoMessage() {}

func (x *UniqueCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueCharacter.ProtoReflect.Descriptor instead.
func (*UniqueCharacter) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *UniqueCharacter) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UniqueCharacter) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UniqueCharacter) GetIs_1P() bool {
	if x != nil {
		return x.Is_1P
	}
	return false
}

func (x *UniqueCharacter) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *UniqueCharacter) GetPositionX() uint32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *UniqueCharacter) GetPositionY() uint32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *UniqueCharacter) GetConditions() []*CharacterCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *UniqueCharacter) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

type CharacterCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConditionId   int32                  `protobuf:"varint,2,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	LastingTurn   int32                  `protobuf:"varint,3,opt,name=lasting_turn,json=lastingTurn,proto3" json:"lasting_turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterCondition) Reset() {
	*x = CharacterCondition{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCondition) ProtoMessage() {}

func (x *CharacterCondition) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCondition.ProtoReflect.Descriptor instead.
func (*CharacterCondition) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *CharacterCondition) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterCondition) GetConditionId() int32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

func (x *CharacterCondition) GetLastingTurn() int32 {
	if x != nil {
		return x.LastingTurn
	}
	return 0
}

type GetGameDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameDataRequest) Reset() {
	*x = GetGameDataRequest{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameDataRequest) ProtoMessage() {}

func (x *GetGameDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameDataRequest.ProtoReflect.Descriptor instead.
func (*GetGameDataRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *GetGameDataRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RegisterCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Is_1P         bool                   `protobuf:"varint,2,opt,name=is_1p,json=is1p,proto3" json:"is_1p,omitempty"`
	CharacterIds  []uint32               `protobuf:"varint,3,rep,packed,name=character_ids,json=characterIds,proto3" json:"character_ids,omitempty"` // 選んだ3体のマスターID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCharactersRequest) Reset() {
	*x = RegisterCharactersRequest{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCharactersRequest) ProtoMessage() {}

func (x *RegisterCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCharactersRequest.ProtoReflect.Descriptor instead.
func (*RegisterCharactersRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterCharactersRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RegisterCharactersRequest) GetIs_1P() bool {
	if x != nil {
		return x.Is_1P
	}
	return false
}

func (x *RegisterCharactersRequest) GetCharacterIds() []uint32 {
	if x != nil {
		return x.CharacterIds
	}
	return nil
}

type RegisterCharactersResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RegisteredCharacters []*UniqueCharacter     `protobuf:"bytes,1,rep,name=registered_characters,json=registeredCharacters,proto3" json:"registered_characters,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterCharactersResponse) Reset() {
	*x = RegisterCharactersResponse{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCharactersResponse) ProtoMessage() {}

func (x *RegisterCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCharactersResponse.ProtoReflect.Descriptor instead.
func (*RegisterCharactersResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterCharactersResponse) GetRegisteredCharacters() []*UniqueCharacter {
	if x != nil {
		return x.RegisteredCharacters
	}
	return nil
}

type FetchActionLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"` // 消失した通し番号を指定してピンポイントに貰う
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchActionLogRequest) Reset() {
	*x = FetchActionLogRequest{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchActionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchActionLogRequest) ProtoMessage() {}

func (x *FetchActionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchActionLogRequest.ProtoReflect.Descriptor instead.
func (*FetchActionLogRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *FetchActionLogRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *FetchActionLogRequest) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GameActionLog struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId                 uint32                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sequence               uint32                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`                                                               // 通し番号（1, 2, 3...）
	PlayerId               string                 `protobuf:"bytes,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`                                                // 行動したプレイヤーID
	ActionType             string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`                                          // "MOVE" または "ATTACK"
	ActorCharacterUniqueId uint32                 `protobuf:"varint,6,opt,name=actor_character_unique_id,json=actorCharacterUniqueId,proto3" json:"actor_character_unique_id,omitempty"` // 行動したキャラのID
	// （action_type == "MOVE" の時のみ使用）
	ToX uint32 `protobuf:"varint,7,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY uint32 `protobuf:"varint,8,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	// （action_type == "ATTACK" の時のみ使用）
	AttackType               int32    `protobuf:"varint,9,opt,name=attack_type,json=attackType,proto3" json:"attack_type,omitempty"`
	TargetCharacterUniqueIds []uint32 `protobuf:"varint,10,rep,packed,name=target_character_unique_ids,json=targetCharacterUniqueIds,proto3" json:"target_character_unique_ids,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GameActionLog) Reset() {
	*x = GameActionLog{}
	mi := &file_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameActionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameActionLog) ProtoMessage() {}

func (x *GameActionLog) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameActionLog.ProtoReflect.Descriptor instead.
func (*GameActionLog) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *GameActionLog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameActionLog) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GameActionLog) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GameActionLog) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameActionLog) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *GameActionLog) GetActorCharacterUniqueId() uint32 {
	if x != nil {
		return x.ActorCharacterUniqueId
	}
	return 0
}

func (x *GameActionLog) GetToX() uint32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *GameActionLog) GetToY() uint32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

func (x *GameActionLog) GetAttackType() int32 {
	if x != nil {
		return x.AttackType
	}
	return 0
}

func (x *GameActionLog) GetTargetCharacterUniqueIds() []uint32 {
	if x != nil {
		return x.TargetCharacterUniqueIds
	}
	return nil
}

type ApplyEffectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CharacterId   uint32                 `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	EffectType    int32                  `protobuf:"varint,4,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"`
	NewHp         uint32                 `protobuf:"varint,5,opt,name=new_hp,json=newHp,proto3" json:"new_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyEffectRequest) Reset() {
	*x = ApplyEffectRequest{}
	mi := &file_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyEffectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyEffectRequest) ProtoMessage() {}

func (x *ApplyEffectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyEffectRequest.ProtoReflect.Descriptor instead.
func (*ApplyEffectRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyEffectRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ApplyEffectRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ApplyEffectRequest) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *ApplyEffectRequest) GetEffectType() int32 {
	if x != nil {
		return x.EffectType
	}
	return 0
}

func (x *ApplyEffectRequest) GetNewHp() uint32 {
	if x != nil {
		return x.NewHp
	}
	return 0
}

type NewTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewTurnRequest) Reset() {
	*x = NewTurnRequest{}
	mi := &file_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTurnRequest) ProtoMessage() {}

func (x *NewTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTurnRequest.ProtoReflect.Descriptor instead.
func (*NewTurnRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16}
}

func (x *NewTurnRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *NewTurnRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type AcceptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // デバッグ用エラーメッセージなど
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{17}
}

func (x *AcceptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EndTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint32                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndTurnRequest) Reset() {
	*x = EndTurnRequest{}
	mi := &file_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTurnRequest) ProtoMessage() {}

func (x *EndTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTurnRequest.ProtoReflect.Descriptor instead.
func (*EndTurnRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{18}
}

func (x *EndTurnRequest) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *EndTurnRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\fgame.network\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"\x11CreateGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1d\n" +
	"\n" +
	"player1_id\x18\x02 \x01(\tR\tplayer1Id\x12\x1d\n" +
	"\n" +
	"player2_id\x18\x03 \x01(\tR\tplayer2Id\"I\n" +
	"\x11StreamGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"v\n" +
	"\x10GridUpdateAction\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12,\n" +
	"\x05grids\x18\x03 \x03(\v2\x16.game.network.GridInfoR\x05grids\"\x8b\x01\n" +
	"\n" +
	"MoveAction\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\rR\vcharacterId\x12\x11\n" +
	"\x04to_x\x18\x04 \x01(\rR\x03toX\x12\x11\n" +
	"\x04to_y\x18\x05 \x01(\rR\x03toY\"\xd6\x01\n" +
	"\fAttackAction\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x122\n" +
	"\x15attacker_character_id\x18\x03 \x01(\rR\x13attackerCharacterId\x12\x1f\n" +
	"\vattack_type\x18\x04 \x01(\x05R\n" +
	"attackType\x12;\n" +
	"\fattack_infos\x18\b \x03(\v2\x18.game.network.AttackInfoR\vattackInfos\"W\n" +
	"\n" +
	"AttackInfo\x122\n" +
	"\x15attacked_character_id\x18\x01 \x01(\rR\x13attackedCharacterId\x12\x15\n" +
	"\x06new_hp\x18\x02 \x01(\rR\x05newHp\"\xe8\x06\n" +
	"\x10GameDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\rR\x06roomId\x12\x1d\n" +
	"\n" +
	"player1_id\x18\x03 \x01(\tR\tplayer1Id\x12\x1d\n" +
	"\n" +
	"player2_id\x18\x04 \x01(\tR\tplayer2Id\x12\x19\n" +
	"\bbase_hp1\x18\x05 \x01(\rR\abaseHp1\x12\x19\n" +
	"\bbase_hp2\x18\x06 \x01(\rR\abaseHp2\x12\x12\n" +
	"\x04turn\x18\a \x01(\rR\x04turn\x12\x1c\n" +
	"\n" +
	"is_1p_turn\x18\b \x01(\bR\bis1pTurn\x12>\n" +
	"\rturn_start_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vturnStartAt\x12=\n" +
	"\n" +
	"characters\x18\n" +
	" \x03(\v2\x1d.game.network.UniqueCharacterR\n" +
	"characters\x12\x1f\n" +
	"\vis_finished\x18\v \x01(\bR\n" +
	"isFinished\x12(\n" +
	"\x10winner_player_id\x18\f \x01(\tR\x0ewinnerPlayerId\x12;\n" +
	"\vfinished_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12;\n" +
	"\fattack_infos\x18\x0e \x03(\v2\x18.game.network.AttackInfoR\vattackInfos\x12,\n" +
	"\x05grids\x18\x0f \x03(\v2\x16.game.network.GridInfoR\x05grids\x12\x17\n" +
	"\acost_1p\x18\x10 \x01(\rR\x06cost1p\x12\x17\n" +
	"\acost_2p\x18\x11 \x01(\rR\x06cost2p\x12\"\n" +
	"\rp1_rate_delta\x18\x12 \x01(\x05R\vp1RateDelta\x12\"\n" +
	"\rp2_rate_delta\x18\x13 \x01(\x05R\vp2RateDelta\x12\x17\n" +
	"\ap1_rate\x18\x14 \x01(\x05R\x06p1Rate\x12\x17\n" +
	"\ap2_rate\x18\x15 \x01(\x05R\x06p2Rate\x12C\n" +
	"\x0fgame_action_log\x18\x16 \x01(\v2\x1b.game.network.GameActionLogR\rgameActionLog\x12\"\n" +
	"\ris_turn_ended\x18\x17 \x01(\bR\visTurnEnded\"\xae\x01\n" +
	"\bGridInfo\x12\x1d\n" +
	"\n" +
	"position_x\x18\x01 \x01(\rR\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\x02 \x01(\rR\tpositionY\x12\x1b\n" +
	"\tgrid_type\x18\x03 \x01(\x05R\bgridType\x12\x1f\n" +
	"\vis_selected\x18\x04 \x01(\bR\n" +
	"isSelected\x12&\n" +
	"\x0fis_attack_range\x18\x05 \x01(\bR\risAttackRange\"\x8a\x02\n" +
	"\x0fUniqueCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\rR\vcharacterId\x12\x13\n" +
	"\x05is_1p\x18\x03 \x01(\bR\x04is1p\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\rR\x02hp\x12\x1d\n" +
	"\n" +
	"position_x\x18\x05 \x01(\rR\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\x06 \x01(\rR\tpositionY\x12@\n" +
	"\n" +
	"conditions\x18\a \x03(\v2 .game.network.CharacterConditionR\n" +
	"conditions\x12\x1f\n" +
	"\vis_selected\x18\b \x01(\bR\n" +
	"isSelected\"j\n" +
	"\x12CharacterCondition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\fcondition_id\x18\x02 \x01(\x05R\vconditionId\x12!\n" +
	"\flasting_turn\x18\x03 \x01(\x05R\vlastingTurn\"-\n" +
	"\x12GetGameDataRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\"n\n" +
	"\x19RegisterCharactersRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x13\n" +
	"\x05is_1p\x18\x02 \x01(\bR\x04is1p\x12#\n" +
	"\rcharacter_ids\x18\x03 \x03(\rR\fcharacterIds\"p\n" +
	"\x1aRegisterCharactersResponse\x12R\n" +
	"\x15registered_characters\x18\x01 \x03(\v2\x1d.game.network.UniqueCharacterR\x14registeredCharacters\"L\n" +
	"\x15FetchActionLogRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\"\xd3\x02\n" +
	"\rGameActionLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\rR\x06roomId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\rR\bsequence\x12\x1b\n" +
	"\tplayer_id\x18\x04 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\x129\n" +
	"\x19actor_character_unique_id\x18\x06 \x01(\rR\x16actorCharacterUniqueId\x12\x11\n" +
	"\x04to_x\x18\a \x01(\rR\x03toX\x12\x11\n" +
	"\x04to_y\x18\b \x01(\rR\x03toY\x12\x1f\n" +
	"\vattack_type\x18\t \x01(\x05R\n" +
	"attackType\x12=\n" +
	"\x1btarget_character_unique_ids\x18\n" +
	" \x03(\rR\x18targetCharacterUniqueIds\"\xa5\x01\n" +
	"\x12ApplyEffectRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\rR\vcharacterId\x12\x1f\n" +
	"\veffect_type\x18\x04 \x01(\x05R\n" +
	"effectType\x12\x15\n" +
	"\x06new_hp\x18\x05 \x01(\rR\x05newHp\"F\n" +
	"\x0eNewTurnRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"D\n" +
	"\x0eAcceptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x0eEndTurnRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\rR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId2\xf9\x06\n" +
	"\rBattleService\x12M\n" +
	"\n" +
	"CreateGame\x12\x1f.game.network.CreateGameRequest\x1a\x1e.game.network.GameDataResponse\x12O\n" +
	"\vGetGameData\x12 .game.network.GetGameDataRequest\x1a\x1e.game.network.GameDataResponse\x12g\n" +
	"\x12RegisterCharacters\x12'.game.network.RegisterCharactersRequest\x1a(.game.network.RegisterCharactersResponse\x12O\n" +
	"\n" +
	"StreamGame\x12\x1f.game.network.StreamGameRequest\x1a\x1e.game.network.GameDataResponse0\x01\x12C\n" +
	"\tApplyMove\x12\x18.game.network.MoveAction\x1a\x1c.game.network.AcceptResponse\x12G\n" +
	"\vApplyAttack\x12\x1a.game.network.AttackAction\x1a\x1c.game.network.AcceptResponse\x12O\n" +
	"\x0fApplyGridUpdate\x12\x1e.game.network.GridUpdateAction\x1a\x1c.game.network.AcceptResponse\x12M\n" +
	"\vApplyEffect\x12 .game.network.ApplyEffectRequest\x1a\x1c.game.network.AcceptResponse\x12E\n" +
	"\aEndTurn\x12\x1c.game.network.EndTurnRequest\x1a\x1c.game.network.AcceptResponse\x12E\n" +
	"\aNewTurn\x12\x1c.game.network.NewTurnRequest\x1a\x1c.game.network.AcceptResponse\x12R\n" +
	"\x0eFetchActionLog\x12#.game.network.FetchActionLogRequest\x1a\x1b.game.network.GameActionLogB\x1bZ\n" +
	"auxilia/pb\xaa\x02\fGame.Networkb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_game_proto_goTypes = []any{
	(*CreateGameRequest)(nil),          // 0: game.network.CreateGameRequest
	(*StreamGameRequest)(nil),          // 1: game.network.StreamGameRequest
	(*GridUpdateAction)(nil),           // 2: game.network.GridUpdateAction
	(*MoveAction)(nil),                 // 3: game.network.MoveAction
	(*AttackAction)(nil),               // 4: game.network.AttackAction
	(*AttackInfo)(nil),                 // 5: game.network.AttackInfo
	(*GameDataResponse)(nil),           // 6: game.network.GameDataResponse
	(*GridInfo)(nil),                   // 7: game.network.GridInfo
	(*UniqueCharacter)(nil),            // 8: game.network.UniqueCharacter
	(*CharacterCondition)(nil),         // 9: game.network.CharacterCondition
	(*GetGameDataRequest)(nil),         // 10: game.network.GetGameDataRequest
	(*RegisterCharactersRequest)(nil),  // 11: game.network.RegisterCharactersRequest
	(*RegisterCharactersResponse)(nil), // 12: game.network.RegisterCharactersResponse
	(*FetchActionLogRequest)(nil),      // 13: game.network.FetchActionLogRequest
	(*GameActionLog)(nil),              // 14: game.network.GameActionLog
	(*ApplyEffectRequest)(nil),         // 15: game.network.ApplyEffectRequest
	(*NewTurnRequest)(nil),             // 16: game.network.NewTurnRequest
	(*AcceptResponse)(nil),             // 17: game.network.AcceptResponse
	(*EndTurnRequest)(nil),             // 18: game.network.EndTurnRequest
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
}
var file_game_proto_depIdxs = []int32{
	7,  // 0: game.network.GridUpdateAction.grids:type_name -> game.network.GridInfo
	5,  // 1: game.network.AttackAction.attack_infos:type_name -> game.network.AttackInfo
	19, // 2: game.network.GameDataResponse.turn_start_at:type_name -> google.protobuf.Timestamp
	8,  // 3: game.network.GameDataResponse.characters:type_name -> game.network.UniqueCharacter
	19, // 4: game.network.GameDataResponse.finished_at:type_name -> google.protobuf.Timestamp
	5,  // 5: game.network.GameDataResponse.attack_infos:type_name -> game.network.AttackInfo
	7,  // 6: game.network.GameDataResponse.grids:type_name -> game.network.GridInfo
	14, // 7: game.network.GameDataResponse.game_action_log:type_name -> game.network.GameActionLog
	9,  // 8: game.network.UniqueCharacter.conditions:type_name -> game.network.CharacterCondition
	8,  // 9: game.network.RegisterCharactersResponse.registered_characters:type_name -> game.network.UniqueCharacter
	0,  // 10: game.network.BattleService.CreateGame:input_type -> game.network.CreateGameRequest
	10, // 11: game.network.BattleService.GetGameData:input_type -> game.network.GetGameDataRequest
	11, // 12: game.network.BattleService.RegisterCharacters:input_type -> game.network.RegisterCharactersRequest
	1,  // 13: game.network.BattleService.StreamGame:input_type -> game.network.StreamGameRequest
	3,  // 14: game.network.BattleService.ApplyMove:input_type -> game.network.MoveAction
	4,  // 15: game.network.BattleService.ApplyAttack:input_type -> game.network.AttackAction
	2,  // 16: game.network.BattleService.ApplyGridUpdate:input_type -> game.network.GridUpdateAction
	15, // 17: game.network.BattleService.ApplyEffect:input_type -> game.network.ApplyEffectRequest
	18, // 18: game.network.BattleService.EndTurn:input_type -> game.network.EndTurnRequest
	16, // 19: game.network.BattleService.NewTurn:input_type -> game.network.NewTurnRequest
	13, // 20: game.network.BattleService.FetchActionLog:input_type -> game.network.FetchActionLogRequest
	6,  // 21: game.network.BattleService.CreateGame:output_type -> game.network.GameDataResponse
	6,  // 22: game.network.BattleService.GetGameData:output_type -> game.network.GameDataResponse
	12, // 23: game.network.BattleService.RegisterCharacters:output_type -> game.network.RegisterCharactersResponse
	6,  // 24: game.network.BattleService.StreamGame:output_type -> game.network.GameDataResponse
	17, // 25: game.network.BattleService.ApplyMove:output_type -> game.network.AcceptResponse
	17, // 26: game.network.BattleService.ApplyAttack:output_type -> game.network.AcceptResponse
	17, // 27: game.network.BattleService.ApplyGridUpdate:output_type -> game.network.AcceptResponse
	17, // 28: game.network.BattleService.ApplyEffect:output_type -> game.network.AcceptResponse
	17, // 29: game.network.BattleService.EndTurn:output_type -> game.network.AcceptResponse
	17, // 30: game.network.BattleService.NewTurn:output_type -> game.network.AcceptResponse
	14, // 31: game.network.BattleService.FetchActionLog:output_type -> game.network.GameActionLog
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
