// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: room_match.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomMatchService_CreateRoomMatch_FullMethodName = "/roommatch.RoomMatchService/CreateRoomMatch"
	RoomMatchService_ListRoomMatch_FullMethodName   = "/roommatch.RoomMatchService/ListRoomMatch"
	RoomMatchService_UpdateRoomMatch_FullMethodName = "/roommatch.RoomMatchService/UpdateRoomMatch"
)

// RoomMatchServiceClient is the client API for RoomMatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomMatchServiceClient interface {
	CreateRoomMatch(ctx context.Context, in *CreateRoomMatchRequest, opts ...grpc.CallOption) (*RoomMatchResponse, error)
	ListRoomMatch(ctx context.Context, in *ListRoomMatchRequest, opts ...grpc.CallOption) (*ListRoomMatchResponse, error)
	UpdateRoomMatch(ctx context.Context, in *UpdateRoomMatchRequest, opts ...grpc.CallOption) (*RoomMatchResponse, error)
}

type roomMatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomMatchServiceClient(cc grpc.ClientConnInterface) RoomMatchServiceClient {
	return &roomMatchServiceClient{cc}
}

func (c *roomMatchServiceClient) CreateRoomMatch(ctx context.Context, in *CreateRoomMatchRequest, opts ...grpc.CallOption) (*RoomMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomMatchResponse)
	err := c.cc.Invoke(ctx, RoomMatchService_CreateRoomMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomMatchServiceClient) ListRoomMatch(ctx context.Context, in *ListRoomMatchRequest, opts ...grpc.CallOption) (*ListRoomMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomMatchResponse)
	err := c.cc.Invoke(ctx, RoomMatchService_ListRoomMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomMatchServiceClient) UpdateRoomMatch(ctx context.Context, in *UpdateRoomMatchRequest, opts ...grpc.CallOption) (*RoomMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomMatchResponse)
	err := c.cc.Invoke(ctx, RoomMatchService_UpdateRoomMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomMatchServiceServer is the server API for RoomMatchService service.
// All implementations must embed UnimplementedRoomMatchServiceServer
// for forward compatibility.
type RoomMatchServiceServer interface {
	CreateRoomMatch(context.Context, *CreateRoomMatchRequest) (*RoomMatchResponse, error)
	ListRoomMatch(context.Context, *ListRoomMatchRequest) (*ListRoomMatchResponse, error)
	UpdateRoomMatch(context.Context, *UpdateRoomMatchRequest) (*RoomMatchResponse, error)
	mustEmbedUnimplementedRoomMatchServiceServer()
}

// UnimplementedRoomMatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomMatchServiceServer struct{}

func (UnimplementedRoomMatchServiceServer) CreateRoomMatch(context.Context, *CreateRoomMatchRequest) (*RoomMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoomMatch not implemented")
}
func (UnimplementedRoomMatchServiceServer) ListRoomMatch(context.Context, *ListRoomMatchRequest) (*ListRoomMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoomMatch not implemented")
}
func (UnimplementedRoomMatchServiceServer) UpdateRoomMatch(context.Context, *UpdateRoomMatchRequest) (*RoomMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoomMatch not implemented")
}
func (UnimplementedRoomMatchServiceServer) mustEmbedUnimplementedRoomMatchServiceServer() {}
func (UnimplementedRoomMatchServiceServer) testEmbeddedByValue()                          {}

// UnsafeRoomMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomMatchServiceServer will
// result in compilation errors.
type UnsafeRoomMatchServiceServer interface {
	mustEmbedUnimplementedRoomMatchServiceServer()
}

func RegisterRoomMatchServiceServer(s grpc.ServiceRegistrar, srv RoomMatchServiceServer) {
	// If the following call panics, it indicates UnimplementedRoomMatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomMatchService_ServiceDesc, srv)
}

func _RoomMatchService_CreateRoomMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomMatchServiceServer).CreateRoomMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomMatchService_CreateRoomMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomMatchServiceServer).CreateRoomMatch(ctx, req.(*CreateRoomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomMatchService_ListRoomMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomMatchServiceServer).ListRoomMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomMatchService_ListRoomMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomMatchServiceServer).ListRoomMatch(ctx, req.(*ListRoomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomMatchService_UpdateRoomMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomMatchServiceServer).UpdateRoomMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomMatchService_UpdateRoomMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomMatchServiceServer).UpdateRoomMatch(ctx, req.(*UpdateRoomMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomMatchService_ServiceDesc is the grpc.ServiceDesc for RoomMatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomMatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roommatch.RoomMatchService",
	HandlerType: (*RoomMatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoomMatch",
			Handler:    _RoomMatchService_CreateRoomMatch_Handler,
		},
		{
			MethodName: "ListRoomMatch",
			Handler:    _RoomMatchService_ListRoomMatch_Handler,
		},
		{
			MethodName: "UpdateRoomMatch",
			Handler:    _RoomMatchService_UpdateRoomMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room_match.proto",
}
