// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/room_match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IsGaming      bool                   `protobuf:"varint,4,opt,name=is_gaming,json=isGaming,proto3" json:"is_gaming,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMatch) Reset() {
	*x = RoomMatch{}
	mi := &file_proto_room_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMatch) ProtoMessage() {}

func (x *RoomMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMatch.ProtoReflect.Descriptor instead.
func (*RoomMatch) Descriptor() ([]byte, []int) {
	return file_proto_room_match_proto_rawDescGZIP(), []int{0}
}

func (x *RoomMatch) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomMatch) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomMatch) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RoomMatch) GetIsGaming() bool {
	if x != nil {
		return x.IsGaming
	}
	return false
}

type CreateRoomMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IsGaming      bool                   `protobuf:"varint,3,opt,name=is_gaming,json=isGaming,proto3" json:"is_gaming,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomMatchRequest) Reset() {
	*x = CreateRoomMatchRequest{}
	mi := &file_proto_room_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomMatchRequest) ProtoMessage() {}

func (x *CreateRoomMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomMatchRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_match_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomMatchRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateRoomMatchRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateRoomMatchRequest) GetIsGaming() bool {
	if x != nil {
		return x.IsGaming
	}
	return false
}

type RoomMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomMatch             `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMatchResponse) Reset() {
	*x = RoomMatchResponse{}
	mi := &file_proto_room_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMatchResponse) ProtoMessage() {}

func (x *RoomMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMatchResponse.ProtoReflect.Descriptor instead.
func (*RoomMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_match_proto_rawDescGZIP(), []int{2}
}

func (x *RoomMatchResponse) GetRoom() *RoomMatch {
	if x != nil {
		return x.Room
	}
	return nil
}

type ListRoomMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomMatchRequest) Reset() {
	*x = ListRoomMatchRequest{}
	mi := &file_proto_room_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomMatchRequest) ProtoMessage() {}

func (x *ListRoomMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomMatchRequest.ProtoReflect.Descriptor instead.
func (*ListRoomMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_match_proto_rawDescGZIP(), []int{3}
}

type ListRoomMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomMatch           `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomMatchResponse) Reset() {
	*x = ListRoomMatchResponse{}
	mi := &file_proto_room_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomMatchResponse) ProtoMessage() {}

func (x *ListRoomMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomMatchResponse.ProtoReflect.Descriptor instead.
func (*ListRoomMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_match_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoomMatchResponse) GetRooms() []*RoomMatch {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_proto_room_match_proto protoreflect.FileDescriptor

const file_proto_room_match_proto_rawDesc = "" +
	"\n" +
	"\x16proto/room_match.proto\x12\troommatch\"y\n" +
	"\tRoomMatch\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1b\n" +
	"\tis_gaming\x18\x04 \x01(\bR\bisGaming\"m\n" +
	"\x16CreateRoomMatchRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tis_gaming\x18\x03 \x01(\bR\bisGaming\"=\n" +
	"\x11RoomMatchResponse\x12(\n" +
	"\x04room\x18\x01 \x01(\v2\x14.roommatch.RoomMatchR\x04room\"\x16\n" +
	"\x14ListRoomMatchRequest\"C\n" +
	"\x15ListRoomMatchResponse\x12*\n" +
	"\x05rooms\x18\x01 \x03(\v2\x14.roommatch.RoomMatchR\x05rooms2\xba\x01\n" +
	"\x10RoomMatchService\x12R\n" +
	"\x0fCreateRoomMatch\x12!.roommatch.CreateRoomMatchRequest\x1a\x1c.roommatch.RoomMatchResponse\x12R\n" +
	"\rListRoomMatch\x12\x1f.roommatch.ListRoomMatchRequest\x1a .roommatch.ListRoomMatchResponseB\fZ\n" +
	"auxilia/pbb\x06proto3"

var (
	file_proto_room_match_proto_rawDescOnce sync.Once
	file_proto_room_match_proto_rawDescData []byte
)

func file_proto_room_match_proto_rawDescGZIP() []byte {
	file_proto_room_match_proto_rawDescOnce.Do(func() {
		file_proto_room_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_room_match_proto_rawDesc), len(file_proto_room_match_proto_rawDesc)))
	})
	return file_proto_room_match_proto_rawDescData
}

var file_proto_room_match_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_room_match_proto_goTypes = []any{
	(*RoomMatch)(nil),              // 0: roommatch.RoomMatch
	(*CreateRoomMatchRequest)(nil), // 1: roommatch.CreateRoomMatchRequest
	(*RoomMatchResponse)(nil),      // 2: roommatch.RoomMatchResponse
	(*ListRoomMatchRequest)(nil),   // 3: roommatch.ListRoomMatchRequest
	(*ListRoomMatchResponse)(nil),  // 4: roommatch.ListRoomMatchResponse
}
var file_proto_room_match_proto_depIdxs = []int32{
	0, // 0: roommatch.RoomMatchResponse.room:type_name -> roommatch.RoomMatch
	0, // 1: roommatch.ListRoomMatchResponse.rooms:type_name -> roommatch.RoomMatch
	1, // 2: roommatch.RoomMatchService.CreateRoomMatch:input_type -> roommatch.CreateRoomMatchRequest
	3, // 3: roommatch.RoomMatchService.ListRoomMatch:input_type -> roommatch.ListRoomMatchRequest
	2, // 4: roommatch.RoomMatchService.CreateRoomMatch:output_type -> roommatch.RoomMatchResponse
	4, // 5: roommatch.RoomMatchService.ListRoomMatch:output_type -> roommatch.ListRoomMatchResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_room_match_proto_init() }
func file_proto_room_match_proto_init() {
	if File_proto_room_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_room_match_proto_rawDesc), len(file_proto_room_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_match_proto_goTypes,
		DependencyIndexes: file_proto_room_match_proto_depIdxs,
		MessageInfos:      file_proto_room_match_proto_msgTypes,
	}.Build()
	File_proto_room_match_proto = out.File
	file_proto_room_match_proto_goTypes = nil
	file_proto_room_match_proto_depIdxs = nil
}
